### ISSUE TITLE
Add versioned docker images based on rocker/r-ver base images

### ISSUE THREAD

**Issue by nihonjinrxs** [rstudio/plumber#117]
It would be great for production deployment to have a docker image for plumber based on the r-ver images from rocker-org.  That way, code can be version-stable between container builds.

Seems like it should be a one-line change in the Dockerfile, and probably entails more work on the Docker Hub side than anything else.

Any chance you could provide that as an officially sanctioned option via Docker Hub?

**Comment by trestletech** [comment]
You're saying you want the plumber Docker images pinned to the R versions? Or that you want them versioned by plumber release?

I guess I'm open to either, but I'm not sure how to go about provisioning this kind of parameterized Docker image on DockerHub. If you have pointers or want to open a PR I'd be interested.

**Comment by FvD** [comment]
What works for me is to pin the r version with [r-ver from rocker](https://hub.docker.com/r/rocker/r-ver/) and then pin the plumber version (and those of other packages) with `devtools` like so:

    RUN R -e "install.packages('devtools')"
    RUN R -e "devtools::install_version('plumber', version = '0.3.2', repos = 'https://cloud.r-project.org/')"

Maybe it makes sense to base a series of public images on separate plumber versions, but I could imagine that just documenting the process to fix the version with a reference to r-ver could be just as helpful. Plumber is likely to be only one of a list of package for most projects.

**Comment by nihonjinrxs** [comment]
Yep, I'm doing something similar now, but it would be nice to have a public image (or a set of them) where that's already done.  If you include `plumber`, `jsonlite`, and the hadleyverse packages, I expect that should cover most cases.  Any other packages could certainly be added on top in a Dockerfile derived from one of those images.

**Comment by nihonjinrxs** [comment]
@trestletech I'm thinking versions of R, but that also should mean that whatever most appropriate version of plumber is pinned as well.  The rocker/r-ver images use MRAN, so I believe that means they're pulling from a set collection of packages pinned to a particular date archive of CRAN.

**Comment by nuest** [comment]
You can add multiple tags based (even based on environment variables) on Docker Hub with build hooks, so you could create tags based on the R version, based on the `plumber` version (extracted from the description file), or both.

I've done this for other repos and would be glad to help out once you agree on a tagging scheme, though it's not that hard, see https://github.com/o2r-project/o2r-muncher/compare/135330bdf47e8fd0cc2d08838d54fa8652bef0e6...c7b2a0789059e734d057ecda6d7b8193f0e9724e (

**Comment by FvD** [comment]
@nuest  that looks really cool! Do I understand correctly that you fix all your package versions in the [package.json](https://github.com/o2r-project/o2r-muncher/blob/master/package.json) file? Does this automatically tag a  production (`dependencies`) and development (`devDependencies`) environment?

**Comment by schloerke** [comment]
Fixed in https://github.com/rstudio/plumber/pull/589
