### ISSUE TITLE
Swagger errors on non-Markup routes

### ISSUE THREAD

**Issue by scottmmjackson** [rstudio/plumber#140]
Reproduce:

```
router <- plumber::plumb(<something>)
router::handle("GET","/somenewroute", function () "Hi there, buddy")
router::run(host = HOST, port = PORT, swagger = TRUE)
```
At `__swagger__`:

![screen shot 2017-07-19 at 10 41 28 am](https://user-images.githubusercontent.com/1735264/28373044-5093816c-6c6f-11e7-8a48-e848a63dfce5.png)

![screen shot 2017-07-19 at 10 41 57 am](https://user-images.githubusercontent.com/1735264/28373050-5330585a-6c6f-11e7-9781-6512eb7741da.png)

**Comment by schloerke** [comment]
Reprex using plumber v1.0.0

```
pr() %>% pr_get("/test", function(){ Sys.time() }) %>% pr_run(port = 8000)
```

No issues seen. Closing
