### ISSUE TITLE
Messaging unclear when listening on 127.0.0.1/0.0.0.0

### ISSUE THREAD

**Issue by JsizzleR** [rstudio/plumber#192]
When attempting to bind to 0.0.0.0, plumber listens on 127.0.0.1.

```
> plumber::plumb("myfile.R")$run(host="0.0.0.0", port=9000)
Starting server to listen on port 9000
Running the swagger UI at http://127.0.0.1:9000/__swagger__/
```

When attempting to listen on a valid external IP, plumber listens on that specified IP.  
Issue occurs on Linux and windows host.

```
> packageVersion("plumber")
[1] ‘0.4.2’
```

**Comment by trestletech** [comment]
So listening on `0.0.0.0` and `127.0.0.1` will likely both print the same message (since we have no better address to send you to other than `127.0.0.1`. The difference is just whether or not the service is going to accept public requests (as is the case with `0.0.0.0`) or only listen for traffic on localhost.

Are you seeing discrepancies in that behavior, or just finding the messaging confusing?

**Comment by JsizzleR** [comment]
Thanks for explaining that, the behavior is as expected.

```
> plumber::plumb("myfile.R")$run(host="0.0.0.0", port=9000)
Starting server to listen on port 9000
Running the swagger UI at http://127.0.0.1:9000/__swagger__/
```


```
[root]# netstat -plant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      27204/rsession
```

**Comment by trestletech** [comment]
Cool. So in that case is it fair to say that the issue here is just that the messaging is unclear regarding whether or not you're listening publicly?

**Comment by JsizzleR** [comment]
Yes, that's describes it exactly, thank you

**Comment by schloerke** [comment]
In `plumber` v1.0.0, the messaging is 

```
pr() %>% pr_get("/test", function(){ Sys.time() }) %>% pr_run(host = "0.0.0.0")
#> Running plumber API at http://0.0.0.0:3616
#> Running swagger Docs at http://127.0.0.1:3616/__docs__/
```

Closing
