### ISSUE TITLE
Plumber can't parse top-level JSON arrays

### ISSUE THREAD

**Issue by trestletech** [rstudio/plumber#236]
As pointed out here: https://stackoverflow.com/questions/48667477/how-do-i-consume-an-array-of-json-objects-using-plumber-in-r

We currently look for a JSON object with named fields but can't do anything special with an unnamed array. Is there a way we could forward that in to a parameter?

**Comment by cardosop** [comment]
Hello friend, 

I am with the same issue, I am not being able to input JSON arrays, seems like the JSON parser is broken. Do you got any answer from the developers or did you managed to workaround on any way?

Thanks!

**Comment by PedroS11** [comment]
Any workaround found? I needed to input an JSON array and I can't do it.

**Comment by PedroS11** [comment]
Yes, I did, thank you.

**Comment by schloerke** [comment]
In Plumber v1.0.0, unnamed arguments are passed through. In addition, you can see the values in `req$argsBody` and `req$args`
