### ISSUE TITLE
[request] fork for interactive use

### ISSUE THREAD

**Issue by r2evans** [rstudio/plumber#249]
Motivation:

- https://stackoverflow.com/questions/49638437/how-do-i-construct-http-requests-in-r-for-testing#49638437 (not my question)

- working model in `opencpu`, how starting a server forks with [`ocpu_start_server()`](https://github.com/opencpu/opencpu/blob/9f5fa63cf09d037bc3865560a2016d09583dbaa2/R/start.R#L53-L76), using `parallel`

For interactive use (e.g., learning, unit-testing), it would be nice to be able to start an instance of `plumber` and immediately return to an R prompt. It may not scale well (`opencpu` is single-thread when run this way), but that is not a safe assumption anyway for console work like this.

**Comment by trestletech** [comment]
Cool. With the new httpuv work we'd actually get this for free. Once the httpuv stuff lands on CRAN I could probably pick this up with minimal effort. Perhaps a `run_background()` method, or something.

**Comment by r2evans** [comment]
I wasn't aware of updates to `httpuv`, does that come with this already baked in? That's nice ... even nicer when it's a benefit you don't have to maintain :-)

**Comment by schloerke** [comment]
While `httpuv` can be run in the background thread, I think the cleanest solution is described here using `callr`: https://github.com/rstudio/plumber/issues/451#issuecomment-652141358
... which shows off this file: https://github.com/blairj09-talks/ppp/blob/bcce1cab0931a4ed6f7787f318fe1dbdf9392b3a/tests/testthat/test-plumber.R
