### ISSUE TITLE
Does plumber support json streams

### ISSUE THREAD

**Issue by david-waterworth** [rstudio/plumber#251]
Hi,

My service processes data in a loop, the data generated from each loop iteration is independent and can be returned to the client immediately.  Is there any way I can access the response stream and write the intermediate response to it using jsonlite::stream_out? 

https://www.rdocumentation.org/packages/jsonlite/versions/1.5/topics/stream_in%2C%20stream_out

Regards
Dave

**Comment by trestletech** [comment]
Good request. This isn't possible today and I'm not sure if the underlying httpuv library would support it, but I'll leave this ticket open to explore in the future.

**Comment by schloerke** [comment]
Plumber does not currently support websockets. If/When it does, this will be one of the first things implemented. 

Going to mark as will not fix (for now)
