### ISSUE TITLE
error im pm2 

### ISSUE THREAD

**Issue by sajukassim** [rstudio/plumber#257]
when I am running plumber on pm2, i got the below error
[PM2][ERROR] Interpreter Rscript does not seem to be available
Please help

[PM2] Spawning PM2 daemon with pm2_home=C:\Users\HP\.pm2
[PM2] PM2 Successfully daemonized
[PM2][ERROR] Interpreter Rscript does not seem to be available
[PM2] Starting C:\sAJUDENTICK\run-myfile.R in fork_mode (1 instance)
[PM2] Done.

**Comment by sajukassim** [comment]
It works when I run the pm2 strat command from the directory C:\Program Files\R\R-3.4.3\bin, it works..

**Comment by schloerke** [comment]
Unable to reprex. Closing
