### ISSUE TITLE
Improved swagger (Docstrings?)

### ISSUE THREAD

**Issue by EDiLD** [rstudio/plumber#275]
I have the impresseion the swagger/openapi funtionality is not fully implemented.
E.g. parameter for POST body defintion, as in http://petstore.swagger.io/#/pet/addPet.

```
#* @param body:body*
```

will give an error.

The approach in RRestserve http://restrserve.org/quick-start.html#swagger_ui_and_openapi via docstrings seems more flexible, but more ugly to write/ maintain.

Any ideas how to improve this in plumber? I like the roxygen style, but it needs much more functionality. If you point me in the correct direction, I could try to prepare a PR...

**Comment by EDiLD** [comment]
It's not only about body, but also about full implementation of swagger & openapi specification.

**Comment by schloerke** [comment]
Closing as arrays are now supported and the router object can also set the openapi yaml information using `pr_set_api_spec()`
