### ISSUE TITLE
Website doesn't render correctly on mobile

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#278]
I've noticed when trying to read through the documentation available on the website the menu bar doesn't collapse and obscures some of the screen. I've noticed this using both chrome and Safari on iOS:

![img_7894](https://user-images.githubusercontent.com/10444878/42601984-ce0757a8-8524-11e8-9119-331d5466d5e9.PNG)
![img_7893](https://user-images.githubusercontent.com/10444878/42601985-ce21fc52-8524-11e8-96c1-d1d4a1aae8fc.PNG)

**Comment by schloerke** [comment]
Closing as docs now use pkgdown
