### ISSUE TITLE
Stream large data

### ISSUE THREAD

**Issue by dipterix** [rstudio/plumber#308]
Thanks for designing such a wonderful package. I plan to use it in my project. However, there are some bottlenecks.

I need to send 400MB data (generated by R) from data server to logic server via intranet within 5 seconds. However, serializing data to JSON is too slow. 

Is there any native support to send binary content type (application/octet-stream)? Right now I'm planning to fast serialize the data into binary files and change the response header to receive the file and unserialize. 

Best.

**Comment by dipterix** [comment]
To be clear. I want to use `plumber` as "data servers" to collect and clean data. This process is usually fast but requires large RAM and secured connections. I also have many logic servers running with algorithms (slow, blocking) and one shiny server to monitor these logic servers. 

```
                             +------ (module 1)--+
(shiny server, non-blocking)-+------ (module 2)--+-(data server / database, large dataset)
                             |------ (module 3)--|
                             | ...               |
                             +------ (module n)--+
```

The fastest serialization method I found via the internet is `fst`. However, that package must work with a file system instead of connections (I guess it has its own way to deal with multi-thread writing). 

It'll be quite strong if `plumber` can support binary streaming and serialization internally via memory.

**Comment by shrektan** [comment]
@dipterix I believe you are only use plumber to provide an API to another R user (maybe yourself), right? You may use `base::serialize()` to do that. I've tested an R data.table with size over 700MB and it costs only 5 seconds on my computer. Moreover, it's flawless!

You may find more info on my just-add PR #345 . Hope it solves your problem.

**Comment by dipterix** [comment]
To correct, `app0` is not running locally. It's running, listening to a public port.

**Comment by dipterix** [comment]
You are right I've already solved the first question. The problem is my data is generated dynamically with 100-500 chunks, each chunk is 400MB~800MB. I guess I might need a database :/

**Comment by dipterix** [comment]
ah, didn't see your last comment. You are right. Thanks for the help 👍
