### ISSUE TITLE
Where can I find logged outputs on DigitalOcean? 

### ISSUE THREAD

**Issue by emadretina** [rstudio/plumber#309]
This is an amazing package and has very detailed documentation. One issue I am trying to figure out is how to get to the log files when deployed on DigitalOcean. I tried logging on to the console and looks in `/vars/log/` directory but didn't find anything. 

Would be cool if there was a `rsconnect::showLogs(streaming = TRUE)` type command for this.

**Comment by schloerke** [comment]
Please check out section [7.5.5 Logs and Management](https://www.rplumber.io/docs/hosting.html#logs-and-management) where it talks about using `pm2` to manage the logs.  

Please let me know if this solves your issue
