### ISSUE TITLE
Expose `pr` object to filters

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#310]
Much like `req` and `res` can be passed to filters and endpoints, it would be nice if the plumbed object (`pr`) was also able to be passed and accessed in filters.

One example use case for this is exposing the Swagger definition based on some filter logic. For instance, an authentication filter could check for auth and, if it's not there, return `pr$swaggerFile()` so that the Swagger UI can still be generated.

**Comment by schloerke** [comment]
I'm thinking it would be interesting to attach it to the req object.  Something similar to expressjs's [`req.app`](https://expressjs.com/en/4x/api.html#req.app)

**Comment by jcheng5** [comment]
Do if easy
