### ISSUE TITLE
Endpoint evaluated twice with png and jpeg annotations

### ISSUE THREAD

**Issue by emilpl** [rstudio/plumber#349]
Hi, 

it seems that an entire endpoint is evaluated twice in case of graphical output (when `@jpeg` or `@png` annotations are used). This can be confirmed by using the `browser()` command or by simple examples below. 
Example: 
```
#* @jpeg
#* @get /jpeg
function() {
    print("jpeg output")
    plot(1:10)
}
```

Text "jpeg output" is printed to R console twice. 

On the other hand the text prints out only once in this example: 
```
#* @get /simple_sum
function() {
  print("simple sum")
  a <- 2
  b <- 3
  list(Sum = a + b)
}
```

I am using plumber 0.4.7. 
Is there any way to achieve single evaluation also for endpoints with graphic output? 
I don't mind the machine doing the task twice, but it can become problematic time-wise when using ggplot2 with a little larger sample size.

**Comment by schloerke** [comment]
Can not reproduce in v1.0.0 

Closing
