### ISSUE TITLE
Feature request: Restart server on save 

### ISSUE THREAD

**Issue by RobertMyles** [rstudio/plumber#363]
Thanks for the handy package! 

Not sure if this is possible from plumbr, but it would be convenient for the server to restart upon saving a change to the file that is being "`plumb`d".  For instance, if I forget to include a call to `library()` for a package that is used in the script, I'll get `{"error":["500 - Internal server error"]}`. If I go back to include it, and then save the file, it would be cool for plumbr to start the server again, as happens with node, for example, without me having to kill the Rscript.exe process and run it again.

**Comment by schloerke** [comment]
While this is the original issue, closing here and moving to https://github.com/rstudio/plumber/issues/488
