### ISSUE TITLE
Gzip encoding

### ISSUE THREAD

**Issue by jhaynie** [rstudio/plumber#368]
I'm trying to add a filter to support API requests that have gzip encoding. I can't seem to get it to work after many attempts.

Here's example filter I wrote to see if I could gunzip the JSON payload:

```
#* Potentially uncompress body
#* @filter gzip
function(req) {
    if (req$HTTP_CONTENT_ENCODING == "gzip") {
        req$rook.input$rewind()
        buf <- req$rook.input$read()
        req$postBody <- memDecompress(buf, type="gzip")
    }
    plumber::forward()
}
```

In this case, I get a `<simpleError in memDecompress(buf, type = "gzip"): internal error -3 in memDecompress(2)>` when I tries to decompress the raw buffer.

I've validated that the incoming gzip data is correct.

Any ideas?

**Comment by MathieuVn** [comment]
Hey @jhaynie, did you figure out any solution for this problem? Thanks

**Comment by MathieuVn** [comment]
For the record, this piece of code did the job on my side:
```
if (req$HTTP_CONTENT_ENCODING == "gzip"){
    req$rook.input$rewind()
    buf <- req$rook.input$read(req$HTTP_CONTENT_LENGTH)
    req$postBody <- memDecompress(buf, type = "gzip")
}
```
