### ISSUE TITLE
Error calling echo verb while using plumber package sample

### ISSUE THREAD

**Issue by ssabat** [rstudio/plumber#382]
I am trying plumber package on MacOS. I loaded plumber.R file in Rstudio 1.1.463  on R 3.5.1.
Sum verb output is ok, but echo fails.

Here is my output. 

$ curl --data "a=4&b=3" "http://localhost:8000/sum"
[7]
$ curl "http://localhost:8000/echo?msg=hello"
{"error":["404 - Resource Not Found"]}

Have others seen the error?

Thanks,

Sunil

**Comment by schloerke** [comment]
Hi Sunil,

What is the content of your plumber.R file?

- Barret

**Comment by schloerke** [comment]
Closing stale question
