### ISSUE TITLE
plumber.R shouldn't be a requirement if there's a valid entrypoint.R file

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#392]
When a directory is plumbed (`plumber::plumb(dir = "/path/to/dir")`), Plumber looks for an `entrypoint.R` file that returns a runnable Plumber router and a `plumber.R` file that contains the logic for the Plumber router.

However, if the directory looks like this:
```
├── entrypoint.R
└── foo.R
```

Where `foo.R` contains the definition of the Plumber API and `entrypoint.R` "plumbs" `foo.R`, Plumber will complain when `plumber::plumb(dir = '.')` is run because a `plumber.R` file isn't found:
```r
 #> Error in plumber::plumb(dir = ".") :
 #>  No plumber.R file found in the specified directory: .
```
I think instead Plumber should run if a valid `entrypoint.R` file is found, regardless of whether the accompanying API definition is named `plumber.R`. If no `entrypoint.R` file is present, then I think it remains valid to enforce the `plumber.R` naming convention.

**Comment by jcheng5** [comment]
Let's include this in v0.5.0 only if it's a simple fix

**Comment by blairj09** [comment]
This issue came up again today. The [documentation on mounting routers](https://www.rplumber.io/docs/programmatic-usage.html#mount-static) illustrates an API that is created by combining `users.R` with `products.R`. Presumably, the programmatic mounting of these routers would happen in `entrypoint.R`. However, given that the resulting directory would look like this:
```
├── entrypoint.R
├── users.R
└── products.R
```
trying to `plumb()` the directory fails for the reasons described in this issue.
