### ISSUE TITLE
Deloy the plumber at windows system by Rscripts

### ISSUE THREAD

**Issue by chengfeifan** [rstudio/plumber#393]
I try to run plumber in the windows 10, this is the `pumber.R` :
```
library(plumber)

#* Return the sum of two number
#* @param a The first number to add
#* @param b The second number to add
#* @get /sum
function(a,b){
  as.numeric(a) + as.numeric(b)
}
```

And I run the file by the file `runPlumber.R`:

```
library(plumber)
print('done')
r = plumb("Path/pumber.R")
r$run(host='0.0.0.0',port = 8080, swagger = TRUE)
# print('done')
```
I open the `cmd`, and type `Rscript runPlumber.R`, the file is running, then `exit`, but I can not get acess to `http://127.0.0.1:8080/sum?a=1&b=2`

**Comment by schloerke** [comment]
Does it work within a regular R session, rather than an Rscript?

**Comment by chengfeifan** [comment]
Yes, it works with a regular R session. To deploy the `runPlumber.R` in the Windows System, I have to use `Rscript`.

**Comment by shrektan** [comment]
Do you have multiple versions of R installed? Please be sure you are using the same R version. I use windows and plumber works fine for me.

**Comment by schloerke** [comment]
Closing due to lack of communication
