### ISSUE TITLE
GetConsoleMOde on STD_INPUT_HANDLE

### ISSUE THREAD

**Issue by coryhogan** [rstudio/plumber#406]
Hi,

I get this error when I try to run do_provision on a droplet in DigitalOcean. 

![image](https://user-images.githubusercontent.com/29295017/54882974-e987d980-4e2d-11e9-8de9-b60d6e776c10.png)

It just hangs there and does nothing. It's definitely something to do with the debian functions in analogsea. Is it an error on my end or in the packages?

**Comment by schloerke** [comment]
I have not seen this error before.

There was an awkward time where `analogsea` had updated and `plumber` had not. However, I was able to launch a DigitalOcean instance using http://github.com/meztez/plumberDeploy at the launch of `plumber` v1.0.0

Closing
