### ISSUE TITLE
Adding a serializer twice should present warning not error

### ISSUE THREAD

**Issue by schloerke** [rstudio/plumber#410]
Fixes https://github.com/trestletech/plumber/issues/344#issuecomment-480187349

> The code below:
> `plumber::addSerializer("csv", serializer_csv)`
> ...throws an error if it's done a second time "Already have a serializer by the name of csv".
> How can I check the serializers first to see if this exists, or enforce it to be overridden?

- [ ] Add a force argument
- [ ] warn if serializer name already exists
- [ ] function to display serializers

**Comment by willwright76** [comment]
I thought I found a workaround with th e below:

`if (is.null(plumber::plumber$parent_env$.globals$serializers$csv)){
  plumber::addSerializer("csv", serializer_csv)
}`

...but now I'm getting below error?:

`Error in errorHandler(req, res, e) : 
  argument "errorHandler" is missing, with no default`

Note - my code is just as the original example:

`serializer_csv <- function(){
  function(val, req, res, errorHandler){
    tryCatch({
      res$setHeader("Content-Type", "text/plain")
      res$setHeader("Content-Disposition", 'attachment; filename="xxx.csv"')
      res$body <- paste0(val, collapse="\n")
      return(res$toResponse())
    }, error=function(e){
      errorHandler(req, res, e)
    })
  }
}

if (is.null(plumber::plumber$parent_env$.globals$serializers$csv)){
  plumber::addSerializer("csv", serializer_csv)
}`

**Comment by schloerke** [comment]
Fixed in https://github.com/rstudio/plumber/pull/585

```r
register_serializer("NAME", FUNC, verbose = FALSE)
```
