### ISSUE TITLE
Consider linking plumber back as a swagger tool

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/plumber#423]
This site does not contain a *single* R reference:

https://swagger.io/tools/open-source/open-source-integrations/

 Maybe plumber should be added?

**Comment by schloerke** [comment]
I'm wondering if `swagger` R package should be added as well.

Plumber looks like it would qualify similar to `goa`.

**Comment by schloerke** [comment]
PR: https://github.com/swagger-api/swagger.io/pull/286
