### ISSUE TITLE
Install libsodium-dev in Dockerfile

### ISSUE THREAD

**Issue by antoine-sachet** [rstudio/plumber#425]
Since PR #404, the sodium library is used which requires `libsodium-dev` to be installed.
It should be added to the `Dockerfile`.

**Comment by schloerke** [comment]
Fixed in #531

**Comment by philibe** [comment]
For Ubuntu 20.04.1 LTS **without Docker**,  I had an issue to install libsodium-dev for plumber 1.0.0 :

-  `sudo apt-get install libsodium-dev` :
   *  `The following packages have unmet dependencies:  libsodium-dev : Depends: libsodium23 (= 1.0.18-1) but 1.0.18-1+ubuntu16.04.1+deb.sury.org+1 is to be installed (..)`.  
 
I resolved my issue with https://doc.libsodium.org/installation  ie 
- 1)`wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable.tar.gz` 
- 2)`tar xvf libsodium-1.0.18-stable.tar.gz` 
- 3)cd to the dir 
- 4)`./configure` 
- 5)`make && make check` 
- 6)`sudo make install` 
- 7)`install.packages("plumber")` and R plumber 1.0.0 works !
