### ISSUE TITLE
is it possible to create a package that uses plumber?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/plumber#432]
Is it possible to create a package that uses plumber? If so, could you point me to an example?

**Comment by cderv** [comment]
I think this question would be great on the community. There is already a topics on this 

 https://community.rstudio.com/t/plumber-api-and-package-structure/18099/4

New discussion would nice there!

**Comment by schloerke** [comment]
I really like `@julia`'s answer.  

https://community.rstudio.com/t/plumber-api-and-package-structure/18099/6?u=barret

**Comment by schloerke** [comment]
As of `plumber` v1.0.0...

To `plumber::plumb()` `api1` in `mypackage`:
```
plumber::plumb_api("mypackage", "api1")
```

To see the available APIs for `mypackage`, call:
```
# For {mypackage}
plumber::available_apis("mypackage")
#> Available Plumber APIs:
#> * mypackage
#>   - api1
#>   - api2

# For all packages
plumber::available_apis()
#> Available Plumber APIs:
#> * mypackage
#>   - api1
#>   - api2
#> * plumber
#>   - 01-append
#>   - 02-filters
#> ....
```
