### ISSUE TITLE
Need function to run pkg plumber API's

### ISSUE THREAD

**Issue by schloerke** [rstudio/plumber#440]
Given a package structure... https://community.rstudio.com/t/plumber-api-and-package-structure/18099/6?u=barret

Use something similar to ...

```r
pkg_plumb <- function(package, name, ...) {
  plumb(dir = system.file(file.path("plumber", name), package = package))
}
```

... with roxygen docs (and examples?).  

Maybe need to copy the `inst/examples` directory to `inst/plumber/`? (Should follow own pattern)

**Comment by meztez** [comment]
This seems interesting, so basically expose all public function in a package?

Should be pretty simple, loop through exposed objects, when function add handle, when object add static.

makes sense?

**Comment by schloerke** [comment]
> so basically expose all public function in a package?

I don't think so as some APIs should not have all pkg functionality.

I think it's more of a **consistent** way to distribute multiple plumber apis within a single package.  

I think it should be something similar to `learnr::run_tutorial(name, package)`, but I like the api structure of `plumb_pkg(package, name)` (with package before the name).

The solution for `plumb_pkg()` could be as short as the code above. 

--------------

Regarding...
> Maybe need to copy the inst/examples directory to inst/plumber/? (Should follow own pattern)

The plumber's own repo examples `./inst/examples` folder should be moved to `./inst/plumber` so that we can call all plumber examples using the new function.

---------------

To add into this, there should be a `available_apis(package = NULL)` function that inspects for installed apis. See `learnr::available_tutorials(package = NULL)` for an example: https://github.com/rstudio/learnr/blob/9dfe4a94fa3f8e0fa02b35fa55f9bcc0b571c49e/R/available_tutorials.R#L2-L33

If package is not provided, it should return all available apis for all packages.  See: https://github.com/rstudio/learnr/blob/9dfe4a94fa3f8e0fa02b35fa55f9bcc0b571c49e/R/available_tutorials.R#L123-L130 . Yes, this is _slow_, but it is not a critical path for execution.

Given there is no yaml front matter to consume, I think we could just return a data.frame of `package`, `name`.

--------

Then to tie it all off, we could have a print method.  See: https://github.com/rstudio/learnr/blob/9dfe4a94fa3f8e0fa02b35fa55f9bcc0b571c49e/R/available_tutorials.R#L167-L209

I would expect something similar to 

```
PKG:
 - Name1
 - Name2
 - Name3

PKG2:
 - Name1
 - Name2
```

.. but with no other information to consume from the file (ex yaml front matter), maybe the data.frame print method is ok. 🤷

**Comment by schloerke** [comment]
Fixed in https://github.com/rstudio/plumber/pull/631
