### ISSUE TITLE
[Feature Request] Post-Request Hook

### ISSUE THREAD

**Issue by jeffkeller87** [rstudio/plumber#453]
To facilitate update/cleanup operations without causing request blocking. See [this discussion](https://community.rstudio.com/t/plumber-api-scheduled-rmarkdown-etl/33039/8) for motivation.

I'm not 100% sure I'm describing this FR accurately, hopefully @aronatkins can chime in.

**Comment by schloerke** [comment]
I agree with Aron in that you'll have to do the calculation at some point.  Either
* Check before every request and a few people will have slower response times
* Check every `k` seconds and update the data using `later`. This would also _block_ the R process, so new/incoming requests will not be served until the data computation is completed, causing a few people to have slower response times.


There already is a `postroute` hook.  However, all hooks must finish before the request is returned.  What I believe was proposed was to add a hook to run a calculation after the route is processed, but not to block the request from returning.

If plumber implemented this it would require knowledge of `future` and `later` and would require many assumptions by `plumber`.  

Instead, I am inclined to have an example of Option 2 above using `future` with a multisession plan and let the user make the assumptions.  The execution of the `future` process would take up only one of the child cores and returning the data to the master process should not be as bad as calculating the updated data.  (This is similar to running a CRON job on the machine, but it is tied to the plumber router / R session.)

Example setup:
* Enable `future` with a multi core or multi threaded plan.
* Calculate the data right away as the router is created.
* At the end of the calculation, spawn a future process to complete in `k` seconds.
  * Repeat until R session is closed.

Thoughts?

**Comment by jeffkeller87** [comment]
Are multi-session `plumber` instances new? I haven't heard of anything like that before. The approach otherwise seems reasonable to me!

**Comment by schloerke** [comment]
Added with https://github.com/trestletech/plumber/pull/248

No docs yet.  Have not released it to CRAN yet.

**Comment by schloerke** [comment]
I don't think there will ever be a nice, out of the box solution for this problem.

Instead, I'll leave two pseudocode options.

* Perform check after each route is executed.
	* pro: will only check on the data when people are using the router
    * con: The first user will get stale data
```
should_update_flag <- TRUE
pr %>%
	pr_hook("postroute", function(value, req, res) {
		if (should_update(data) && should_update_flag(TRUE)) {
			should_update_flag <<- FALSE
			future::future({
				result <- update_file()
				result
			}) %...>%
				{
					result <- .
					data <<- result
					should_update_flag <<- TRUE
				}
        }
        # return original value
        value
    }) %>%
    pr_run()
```


* Perform check every `k` seconds.
	* pro: calculates data in a background thread
	* pro: only a single thread tied to updating the data
    * con: will ALWAYS be working, even if no one is using the router
```
check_data <- function() {
	if (should_update(data)) {
		# update data
		future::future({
			result <- update_file()
			result
		}) %...>%
			{
				result <- .
				data <<- result
				later::later(function() { check_data() }, delay = k)
			}
    } else {
		later::later(function() { check_data() }, delay = k)
	}
	invisible(TRUE)
}
# kick off the data checking
check_data()
pr %>%
	pr_hook("postroute", function(value, req, res) {
		if (should_update(data)) {
			future::future({
				result <- update_file()
				result
			}) %...>%
				{
					result <- .
					data <<- result
				}
        }
        # return original value
        value
    }) %>%
    pr_run()
```

**Comment by schloerke** [comment]
Closing as I don't think the solution is plumber related, but a data management issue.
