### ISSUE TITLE
Cannot install Debian packages in trestletech/plumber

### ISSUE THREAD

**Issue by cbuchacher** [rstudio/plumber#459]
~Installing curl~ Running `apt-get update` in a Dockerfile based on trestletech/plumber fails with the following error:
```
E: Repository 'http://cdn-fastly.deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'buster' to 'bullseye'
The command '/bin/sh -c apt-get update && apt-get install -t unstable -y curl' returned a non-zero code: 10
```

Maybe a rebuild with a more recent version of debian/testing fixes the issue. However, I think the deeper issue is that a Docker image based on debian/testing will always be prone to instabilities. It would be great if we could have a trestletech/plumber image based on rocker/r-ver.

### Example application *or* steps to reproduce the problem

Dockerfile:
```
FROM trestletech/plumber
RUN apt-get update \
&& apt-get install -t unstable -y curl
RUN apt-get install -y libxml2-dev
COPY . /api
EXPOSE 8000
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(commandArgs()[4]); pr$run(host='0.0.0.0', port=8000, swagger=TRUE)"]
CMD ["/api/plumber.R"]
```

### Describe the problem in detail

```
$ docker build .
Step 1/8 : FROM trestletech/plumber
 ---> f9aa6e6553fb
Step 2/8 : RUN apt-get update && apt-get install -t unstable -y curl
 ---> Running in f8d9f02f20ac
Get:1 http://cdn-fastly.deb.debian.org/debian testing InRelease [117 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian sid InRelease [149 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian sid/main amd64 Packages.diff/Index [27.9 kB]
Ign:3 http://cdn-fastly.deb.debian.org/debian sid/main amd64 Packages.diff/Index
Get:4 http://cdn-fastly.deb.debian.org/debian sid/main amd64 Packages [8,389 kB]
Reading package lists...
E: Repository 'http://cdn-fastly.deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'buster' to 'bullseye'
The command '/bin/sh -c apt-get update && apt-get install -t unstable -y curl' returned a non-zero code: 100
```

**Comment by cbuchacher** [comment]
As a workaround, we are currently doing this:
```
FROM trestletech/plumber
RUN echo 'deb http://deb.debian.org/debian bullseye main' > /etc/apt/sources.list
RUN apt-get update
```

**Comment by mskyttner** [comment]
Here is a Dockerfile for rstudio/plumber based on r-ver:3.6.1:

https://gist.github.com/mskyttner/71948117bbadc16be3cec5f64f18a839

**Comment by mskyttner** [comment]
That Dockerfile should take care of issues #425, #457, #459 and includes usage instructions inlined as comments at the end of it.

**Comment by MarkEdmondson1234** [comment]
Just ran into this, thanks for the solution. (re: https://github.com/MarkEdmondson1234/googleCloudRunner/issues/32 )  

Is there an ETA when the official Docker image will be updated?
