### ISSUE TITLE
Error in do.call(fi$exec, req$args): variable names are limited to 10000 bytes

### ISSUE THREAD

**Issue by RNowak4** [rstudio/plumber#463]
### System details

Output of `sessioninfo::session_info()`:
```
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Polish_Poland.1250          
 ctype    Polish_Poland.1250          
 tz       Europe/Warsaw               
 date     2019-07-19                  

- Packages -----------------------------------------------------------------------
 ! package     * version  date       lib source                              
   assertthat    0.2.1    2019-03-21 [1] CRAN (R 3.6.0)                      
   base64enc   * 0.1-3    2015-07-28 [1] CRAN (R 3.6.0)                      
   cli           1.1.0    2019-03-19 [1] CRAN (R 3.6.0)                      
   crayon        1.3.4    2017-09-16 [1] CRAN (R 3.6.0)                      
   fftw          1.0-5    2019-03-04 [1] CRAN (R 3.6.0)                      
   httpuv        1.5.1    2019-04-05 [1] CRAN (R 3.6.0)                      
   jsonlite      1.6      2018-12-07 [1] CRAN (R 3.6.0)                      
   later         0.8.0    2019-02-11 [1] CRAN (R 3.6.0)                      
   magrittr      1.5      2014-11-22 [1] CRAN (R 3.6.0)                      
   MASS          7.3-51.4 2019-03-31 [2] CRAN (R 3.6.0)                      
 V plumber       0.4.6    2019-07-19 [1] Github (trestletech/plumber@5a5223f)
   promises      1.0.1    2018-04-13 [1] CRAN (R 3.6.0)                      
   R6            2.4.0    2019-02-14 [1] CRAN (R 3.6.0)                      
   Rcpp          1.0.1    2019-03-17 [1] CRAN (R 3.6.0)                      
   remotes       2.1.0    2019-06-24 [1] CRAN (R 3.6.1)                      
   seewave       2.1.3    2019-03-30 [1] CRAN (R 3.6.1)                      
   sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.6.1)                      
   signal        0.7-6    2015-07-30 [1] CRAN (R 3.6.1)                      
   stringi       1.4.3    2019-03-12 [1] CRAN (R 3.6.0)                      
   tuneR         1.3.3    2018-07-08 [1] CRAN (R 3.6.1)                      
   uuid        * 0.1-2    2015-07-28 [1] CRAN (R 3.6.0)                      
   withr         2.1.2    2018-03-15 [1] CRAN (R 3.6.1)                      
```
### Problem description
When I'm trying to send a large text body in POST request (~60kB), sometimes I get an error: `Error in do.call(fi$exec, req$args): variable names are limited to 10000 bytes`.  I found that the problem exists only when text body ends with two characters: `==` (I send big files as base64 text body). The Exception is thrown before entering my controller's code, so i thinkg this is an issue with Plumber. 

### How to reproduce
* Create simple controller:
```
#* @post /test
function (req, res) {
  print("TEST")
  res
}
```
* Send large text as body to that endpoint - example file is 
[here](https://github.com/trestletech/plumber/files/3411199/test.txt). To generate the error, simply add `==` at the end of text in that file.

Regards,
Radek

**Comment by schloerke** [comment]
Hi Radek.  Thank you for the test file.  

Can you give me your `curl` command or R command that you use to reproduce the issue?  Thank you

**Comment by RNowak4** [comment]
> Can you give me your `curl` command or R command that you use to reproduce the issue? 

I use Postman, but `curl` command would be: 
`curl -X POST --data "@test.txt" http://localhost:8000/test`, of course change `path` to `test.txt` file and `host` if necessary. Given file shouldn't generate the error, you need to edit it that content ends with `==`characters.

**Comment by Oduig** [comment]
Just a heads up for anyone reading this, it appears to go wrong when a lot of JSON is minimized to a single line. I can easily send 50 thousand lines to Plumber if it is pretty printed, but the same payload on 1 line without spacing runs into the described error.

Of course, minimized JSON is the best practice for machine-to-machine communication and it's still a bug. But at least there is a workaround!

**Comment by schloerke** [comment]
. @meztez has updated the post body parsers which avoids putting the content of the file as a key in a named list (current CRAN behavior).  


The error is coming from R not allowing variables to have names larger than 10k characters... but is is a reasonable thing to have for file content.  When this ginormous key existed, `do.call` would fail when trying to call the next filter.

--------

Old behavior:
```
❯❯ plumber:::parseBody("randomcharshere") %>% str()
 Named list()
❯❯ plumber:::parseBody("randomcharshere==") %>% str() # bad
List of 1
 $ randomcharshere: chr ""
```

New (and expected) behavior in #532
```
❯❯ parseBody("randomcharshere") %>% str()
 list()
❯❯ parseBody("randomcharshere==") %>% str() # good
 list()
```
