### ISSUE TITLE
Add mounted router `/` route to mounted location if no definition exists

### ISSUE THREAD

**Issue by antoine-sachet** [rstudio/plumber#465]
A trailing slash breaks the endpoint path but is required when accessing a mounted endpoint. This can make the API inconsistent.

Consider:

```R
# plumber.R
#* @get /root
function() {
  rnorm(1)
}
```

```R
# sub_api.R
#* @get /
function() {
  rnorm(1)
}
```

```R
# entrypoint.R
library("plumber")
root <- plumber::plumber$new("plumber.R")
sub_api <- plumber$new("sub_api.R")
root$mount("/sub", sub_api)
root
```

Running the API:

- `url/root` works
- `url/root/` gives a 404
- `url/sub` gives a 404
- `url/sub/` works

Is there a way to make `/sub` be equivalent to `/sub/` and `/root/` to `/root`? Or is it a bad idea?

**Comment by schloerke** [comment]
Are trailing slashes required when visiting regular endpoints?

**Comment by antoine-sachet** [comment]
No, you're right, it's mostly `url/sub` not working which is very annoying as it creates an inconsistent experience for the end user because of an implementation detail. 

It would be nice to have `/root/` work as well (to make life easier for the end user), but this is completely secondary and, if it makes life harder for the programmer, it is not worth it.

**Comment by schloerke** [comment]
I'm in the camp that trailing slashes matter and should be treated as separate routes as they are separate routes.

I also understand the ease of use and common pattern of defining the route once and having it work in both places.  I don't think I can enable it by default at this point, but adding a method (or init flag) would work well and tell of route mismatches.

**Comment by schloerke** [comment]
Closing in favor of #100

**Comment by antoine-sachet** [comment]
I agree with you, the routes are different and should be treated differently. 

However, my point is very different than issue #100 and I disagree with the renaming of this thread to "Trailing slashes should route to the same place".

My core issue is that when you mount an endpoint on `/endpoint`, then `/endpoint` does not actually work. You have to call the mounted endpoint with a trailing slash (`/endpoint/`) and this is very inconsistent, since trailing slashes are not otherwise required.

I maintain a relatively complex API whose main components are broken down in several plumber files and mounted (to e.g. `/report`, `/review`, `/user`, etc.)

People who integrate with our API ask me why they must put a trailing slash to `/report/` (or face a 404) but mustn't put one for all the endpoints below `/report/` (or face a 404). Same thing for `/review/`, `/user/`, etc. 

As far as the end-user is concerned, it seems like some random endpoints take a trailing slash while most others do not. Feels like a leaky abstraction?

**Comment by schloerke** [comment]
Are you wanting the example above to work like the lists below?
* `url/root` works
* `url/root/` gives a 404
* `url/sub` ~~gives a 404~~ works
* `url/sub/` ~~works~~ gives a 404

And if `sub_api` had an `extra` route...
* `url/sub/extra` works


-------------------------------------

The way it currently implemented, you are allowed to have a custom route at `url/sub` with a mounted router starting at `url/sub/`.  

So, would it be good to add the `/` mounted route to the base location? So it would be
* `url/root` works
* `url/root/` gives a 404
* `url/sub` works ; (defined as `url/sub/` if `url/sub` is not already defined)
* `url/sub/` works

**Comment by antoine-sachet** [comment]
Exactly! Sorry I wasn't clear in my initial post where I confounded several issues.

**Comment by schloerke** [comment]
Notes: Should be done at the same time as trailing slashes

**Comment by blairj09** [comment]
This could be accomplished if there was a way to opt-in to redirects on mounted routers:
```r
options(plumber.mount.redirect = TRUE)
```
or
```r
pr_mount(..., redirect = TRUE)
```

Example redirect:
```r
pr_get("/foo", function(res) {
      res$status <- 302
      res$setHeader(name = "Location",
                    value = "/foo/")
      res
    })
```
