### ISSUE TITLE
Encoding problem in Chinese character  when using POST to transmit file

### ISSUE THREAD

**Issue by jaesm14774** [rstudio/plumber#472]
Sorry for I asked problem here again and hope find solution.

# Previously

I build a function which need file path as input and do some pre-processing(cleaning) data and return clean data. If I want to use this function in another computer, I must need to construct some upload file and return download file function by plumber(below picture). However, I don't know how to do it. If only pass parameter like numeric ,txt, json,and .etc I know how to do, but pass file in another computer I don't know how to construct that.

![image](https://user-images.githubusercontent.com/33981395/62767488-5b07b200-bac7-11e9-8f22-10c0ed062c3c.png)

![image](https://user-images.githubusercontent.com/33981395/62767496-66f37400-bac7-11e9-93ab-b6bbe1c4f023.png)

# Main Question:
Until now, I search for a long time and can do that using programming by POST to achieve my goal. But it will make some problems in Chinese. I use python to test R plumber and get below result.

**R plumber(simple function):**

![image](https://user-images.githubusercontent.com/33981395/62767952-55f73280-bac8-11e9-80d8-c4453406ebba.png)

req$postBody
First three line is not important , and end-1 to end line is also not important.
File content will in four to end-2 line, so I do some like this.

**Looks input file**:
![image](https://user-images.githubusercontent.com/33981395/62768175-e46bb400-bac8-11e9-9ea2-9ce75df4e2a4.png)

**Python code**:

![image](https://user-images.githubusercontent.com/33981395/62768234-0107ec00-bac9-11e9-8b73-96e44e5f3b04.png)

Result:
![image](https://user-images.githubusercontent.com/33981395/62768304-25fc5f00-bac9-11e9-9dc2-dc35022e3918.png)

And problem occurred when I use post to api and get wrong encoding.

Result_R_postBody:

print(req$postBody)
![image](https://user-images.githubusercontent.com/33981395/62768438-6e1b8180-bac9-11e9-86bf-a92adb5454f7.png)

# Expected help
Please teach me how to fix the problem or if you know how to do process in upload file and return file more correctly(not use POST), I'm glad of it.

Thanks again for anyone reading entire problem and endure my poor English.

**Comment by jaesm14774** [comment]
I really want to know how to transmit file except using programming read it and pass it.

Like paste file to different path in same computer.

I need original file not processed file by programming.

Hope anyone can teach me,thanks.

**Comment by schloerke** [comment]
POST body handling has been implemented in `v1.0.0`. This should resolve the issue.
