### ISSUE TITLE
customize the swagger route location

### ISSUE THREAD

**Issue by schloerke** [rstudio/plumber#475]
Community post: https://community.rstudio.com/t/change-swagger-url-for-plumber-documentation/37007

**Comment by schloerke** [comment]
Due to integrations in other products, `/__swagger__` can not be changed.  Instead allow for other routes to present the swagger ui in addition to `/__swagger__`

Thanks @blairj09

**Comment by schloerke** [comment]
If users would like to do this, they can call `req$pr$getApiSpec()` in a route of their choice.  However, `/__docs__/*` will always be added

----------

Closing

**Comment by Fuco1** [comment]
@schloerke Can you give an example where to obtain `req` object?  How can I serve my documentation on `host.in/service/docs`.  The issue is that my proxy server routes by path prefix.

**Comment by meztez** [comment]
```r
library(plumber)
pr() |> (function(pr) pr_get(pr, "customdocpath", pr$getApiSpec))() |> pr_run()
```

**Comment by aaronbrezel** [comment]
Is there a way to serve the Swagger UI from this route instead of the raw JSON documenttion?
