### ISSUE TITLE
Add a CSS spinner when loading swagger

### ISSUE THREAD

**Issue by colearendt** [rstudio/plumber#478]
Not sure if updating swagger will immediately give you this type of improvement (https://github.com/trestletech/plumber/issues/422), but I think it'd be great if we got a CSS spinner to suggest that swagger is on its way. On the other hand, perhaps this is impossible if the R process is what is taking time to come up...

Context: hosting Plumber API on RStudio Connect.

**Comment by schloerke** [comment]
When are you wanting the spinner?

* On page load?
* While executing a query?

Currently swagger ui is all done by https://github.com/swagger-api/swagger-ui from the https://github.com/rstudio/swagger R package (v3 ui yet to be released to CRAN)

**Comment by schloerke** [comment]
@colearendt ^^

**Comment by colearendt** [comment]
Oops! Sorry about that! Completely missed that update. Page load was the use case I was thinking of. Silly me didn't look at what was taking the time and whether a spinner is even possible.

**Comment by schloerke** [comment]
That's all owned by swagger ui, so I'm going to say it's not possible.

Even if it's while a query is loading, it's not possible, (also swagger ui).
