### ISSUE TITLE
Requests to valid endpoints with an incorrect request method should return HTTP 405 instead of HTTP 404

### ISSUE THREAD

**Issue by atheriel** [rstudio/plumber#493]
### Example application

Suppose we have the following API:

```R
srv <- plumber::plumber$new()
srv$handle("POST", "/submit", function(req, res) {
  # TODO: Actual work.
  res$headers[["Content-Type"]] <- "text/plain"
  res$body <- "Submitted"
  res
})
srv$run(host = "0.0.0.0")
```

If you send a `GET` request to this API (instead of the `POST` request it is expecting) you see the following (e.g. with `curl`):

```
$ curl -sv -X GET localhost:7312/submit
> GET /submit HTTP/1.1
> Host: localhost:7312
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Mon, 30 Sep 2019 22:15:12 GMT
< Content-Type: application/json
< Date: Mon, 30 Sep 2019 10:15:12 PM GMT
< Content-Length: 38
<
{"error":["404 - Resource Not Found"]}
```

### Describe the problem in detail

There is a well-known and well-supported HTTP status code for the specific issue of "this URI is valid but the method is not", namely `405 Method Not Allowed`. It would be nice if Plumber could support returning this method instead of falling back to 404.

From a cursory look at how routing is implemented, this should be quite possible. It might require that users add a new error handler, though.

**Comment by atheriel** [comment]
@schloerke Does tagging this issue as a bug mean that you would accept a PR?

**Comment by schloerke** [comment]
Yes! I’ll be getting back to plumber here soon.

**Comment by schloerke** [comment]
To be clearer... You’ve found very good bugs. I’d be happy to have any of your contributions.

**Comment by atheriel** [comment]
Oh, that's very kind. I wasn't intending to sound impatient with my comment, I was actually just unsure about what the tags implied.
