### ISSUE TITLE
Sending raw/serialized data

### ISSUE THREAD

**Issue by klarchristian** [rstudio/plumber#502]
Hi,

How can I send serialized data to the server?

I've seen the example to receive serialized data back (https://shrektan.com/post/2018/11/14/use-base-serializer-in-the-plumber-api/ provided by @shrektan) but I can't get the other way working.

Below the code. r_obj_serializer is the registered serializer from the above link. I receive the '20' back, but req is not what I sent in the body.

```
#* @post /api
#* @serializer r_obj_serializer
function(req) { 
  print(req$postBody)
  return(20)
}
```

```
post <- httr::POST(url = "http://localhost:8210/api",
                   body = base::serialize(list(myarg=1),NULL,FALSE),
                   encode='raw',
                   httr::content_type("application/octet-stream"))
```

Here the serializer.

```
plumber::addSerializer("r_obj_serializer", function() {
  function(val, req, res, errorHandler) {
    tryCatch({
      res$setHeader("Content-Type", "application/octet-stream")
      res$body <- base::serialize(val, NULL, ascii = FALSE)
      print('hi')
      return(res$toResponse())
    }, error = function(e) {
      errorHandler(req, res, e)
    })
  }
})
```

Context: I want to be able to send large serialized data objects to docker worker nodes. Using the json serialization takes too long.

Christian

**Comment by shrektan** [comment]
@klarchristian  I just answered a similar question (#512). So I copy & paste the answer here.

- Put the three files in the same folder.
- Run `main.R` to launch a server. 
- Run `client.R` to test.

### plumber.R

```r
#* @post /api
#* @serializer rds
function(req) {
  req$robj
}
```

### main.R

(A better example is this: https://github.com/ozean12/protopretzel/blob/master/R/protobuf_filter.R)

```r
library(plumber)
x <- plumb("plumber.R")
x$filter("robj", function(req) {
  req$rook.input$rewind()
  req$robj <- unserialize(req$rook.input$read())
  plumber::forward()
})
x$run(debug = TRUE, port = 9999)
```

### client.R

```r
out <- httr::POST(
  "http://127.0.0.1:9999/api",
  encode = "raw",
  body = serialize(iris, NULL),
  httr::content_type("application/octet-stream")
)
# you may need to check httr::status_code() == 200L 
# or if is.raw(httr::content(out)) is TRUE, first
base::unserialize(httr::content(out))
```

### What I get

<img width="525" alt="image" src="https://user-images.githubusercontent.com/8368933/77088081-e1fa1100-6a3e-11ea-8bbf-6f1d1e36e301.png">
