### ISSUE TITLE
feature request: To allow optional parameters through @optional annotations or the like

### ISSUE THREAD

**Issue by RevanthNemani** [rstudio/plumber#503]
Hi, 
RPlumber is amazing. As an R programmer, I want to see a day where we switch from spring/nodejs/express APIs to Plumber APIs. It's just amazing and I can focus on the pure business logic. I deployed an enterprise-level app in my bank using RPlumber  (REST + CRUD). Thank you.

I find it hard to set optional parameters. It would be great if we could get an annotation like `@optional NULL/NA/DEFAULT`. So that's optional annotation + what the user wants when the param is not passed.

I hope you find time to make this happen. I'll be waiting for this feature.

Regards
Revanth Nemani

**Comment by schloerke** [comment]
@RevanthNemani Glad you're enjoying plumber!

Please check out the example in https://www.rplumber.io/docs/routing-and-input.html#query-strings

You are allowed to have default values in your route's function definition.  I've copied relevant parts below...

---------------------

```r
#' @get /
search <- function(q="", pretty=0){
  paste0("The q parameter is '", q, "'. ",
         "The pretty parameter is '", pretty, "'.")
}
```

Visiting `http://localhost:8000/?q=bread&pretty=1` will print:

```
["The q parameter is 'bread'. The pretty parameter is '1'."]
```

This is equivalent to calling `search(q="bread", pretty="1")`. If a parameter were not specified in the query string, it would just be omitted from the invocation of the endpoint. For example `http://localhost:8000/?q=cereal` would be equivalent to `search(q="cereal")`

---------------

As a followup to the last statement.... <br />`search(q="cereal")` is the same as `search(q="cereal", pretty = 0)`

Does this solve your request?

**Comment by RevanthNemani** [comment]
Yes, Thanks a lot.

I now see it in 3.6.2 Query Strings in the [documentation](https://www.rplumber.io/docs/routing-and-input.html#the-request-object).


Have a great day
