### ISSUE TITLE
commandArgs()[4] failing for plumber Docker launch: "File does not exist -e"

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rstudio/plumber#511]
A plumber Dockerfile was created that added extra arguments meaning the "boilerplate" `commandArgs()[4]` didn't work for launching the server.

This was discovered after adding some exploratory functions as seen in the screenshots below

![image](https://user-images.githubusercontent.com/3155884/76427956-4ff26880-63ad-11ea-992c-b1a3fd448b96.png)

![image](https://user-images.githubusercontent.com/3155884/76427989-5c76c100-63ad-11ea-81ba-7b945534d420.png)

### Describe the problem in detail

In all my plumber Dockerfiles to date I have launched the server via:

```r
pr <- plumber::plumb(commandArgs()[4]); pr$host(host='0.0.0.0', port=as.numeric(sys.getenv('PORT'))
```

This relies on R being executed via a startup similar to:

```R -e "pr <- plumber::plumb(commandArgs()[4]); pr$host(host='0.0.0.0', port=as.numeric(sys.getenv('PORT'))" api.R```

However in the screenshot above it can be seen `--no-save` and `--no-restore` was inserted, so breaking the positional argument of `commandArgs()` which needed to be `commandArgs()[6]` rather than `commandArgs()[4]` (pointing at the api.R file)

```R --no-save --no-restore -e "pr <- plumber::plumb(commandArgs()[6]); pr$host(host='0.0.0.0', port=as.numeric(sys.getenv('PORT'))" api.R```

My questions are :)

* Would anyone know why this happened when launching R in this Docker container in particular? Can it be suppressed?
* Is it possible to use something more robust than positional arguments in parsing out the command arguments?

**Comment by shizidushu** [comment]
I use `rev` function like below:
`ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(rev(commandArgs())[1]); pr$run(host='0.0.0.0', port=8000, swagger=TRUE)"]`

**Comment by MarkEdmondson1234** [comment]
@shizidushu nice!
