### ISSUE TITLE
Change JSON postBody to data frame and return data frame

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [rstudio/plumber#513]
I want to receive a JSON object, and then covert it into a data frame and do something and then return a data frame.
Something like this:

```
#' @post /test

function(req){
  myData <- fromJSON(req$postBody)
  df <- as.data.frame(myData)
  doSomething(df) #for ex, run a linear regression model
  return(result) # result is a data frame object 
}
```

I have tried a lot of things here and there but it just doesn't work. Can someone help me out?

**Comment by shrektan** [comment]
I believe this is the same question as #512. My answer there should work.
