### ISSUE TITLE
Tailor JSON responses in Post request 

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [rstudio/plumber#514]
I want to return 4 data frames and they are serialised automatically into JSON. But the columns of the Dataframe are being ordered alphabetically. 
That will be a problem when I want to covert it into a table later.

How to solve this?

I need something similar to this.

`{"predictions": [
        {
            "Part_No": "A",
            "Jan.19": 123,
            "Feb.19": 120,
            "Mar.19": 94
        },{
            "Part_No": "A",
            "Jan.19": 123,
            "Feb.19": 120,
            "Mar.19": 94
        }],

   "last_month_error":[
         {"Part_No":"A",
         "error":0.23},
         {"Part_No":"B",
         "error":0.12}
]
}`

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
