### ISSUE TITLE
Using @filter to save responses from one endpoint and call it with another endpoint 

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [rstudio/plumber#515]
I saw [this](https://www.youtube.com/watch?v=pCXYzN0HbwA) video and I want to do something close to this:

I am having trouble using filters however. I want to return like 4 data frames in an endpoint, say \predict and then use them separately by calling 4 different endpoint say \predict\1 and \predict\2 etc.

I am reproducing the code in the video but it's not working
<img width="1074" alt="screen_1" src="https://user-images.githubusercontent.com/60866597/77395370-6e059300-6dc7-11ea-932f-0c70ed6d2a90.png">

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
