### ISSUE TITLE
keyfile parameter in DigitalOcean's related functions

### ISSUE THREAD

**Issue by Adamoso** [rstudio/plumber#524]
Function do_deploy_api() will not work with SSH key outside default location. It would be useful to add the `keyfile` parameter which is available in `droplet_ssh` function from analogsea package.

Thanks for considering.

**Comment by schloerke** [comment]
Don't have permissions to move the issue to meztez/plumberDeploy. So closing here and making a new issue in meztez/plumberDeploy.

See meztez/plumberDeploy#12
