### ISSUE TITLE
Functions within a sourced file are not accessible as API endpoints

### ISSUE THREAD

**Issue by michalskop** [rstudio/plumber#533]
### System details

Output of `sessioninfo::session_info()()`:

```
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Ubuntu 18.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2020-05-04                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 httpuv        1.5.2   2019-09-11 [1] CRAN (R 3.6.3)
 jsonlite      1.6.1   2020-02-02 [1] CRAN (R 3.6.3)
 later         1.0.0   2019-10-04 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
 plumber     * 0.4.6   2018-06-05 [1] CRAN (R 3.6.3)
 promises      1.1.0   2019-10-04 [1] CRAN (R 3.6.3)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.3)
 Rcpp          1.0.4.6 2020-04-09 [1] CRAN (R 3.6.3)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.1)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)

[1] /home/michal/R/x86_64-pc-linux-gnu-library/3.6
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```

### Example application *or* steps to reproduce the problem

main.R:
```R
source("./functions.R")

#* Echo back the input
#* @param msg The message to echo
#* @get /echo
function(msg=""){
  list(msg = paste0("The message is: '", msg, "'"))
}
```

functions.R:
```R
print("I am sourced")
#* Return "hello world"
#* @get /hello
function(){
  "hello world"
}
```

### Describe the problem in detail

I cannot get functions from another (_sourced_) file to be accessible through the API.

My setup is very basic:

main.R:
```R
source("./functions.R")

#* Echo back the input
#* @param msg The message to echo
#* @get /echo
function(msg=""){
  list(msg = paste0("The message is: '", msg, "'"))
}
```

functions.R:
```R
print("I am sourced")
#* Return "hello world"
#* @get /hello
function(){
  "hello world"
}
```

When I run:
```
r = plumb("main.R")
```

I get expected output:
```
[1] "I am sourced"
```

Then I run:
```
r$run(port=8000)
```

And the `/echo` endpoint is accessible, but the `/hello` one is not, returning `404 - Resource Not Found`.

It is the same problem as described here: https://stackoverflow.com/questions/58709539/r-plumber-api-mounted-router-does-not-shows

**Comment by meztez** [comment]
This is not how plumber currently works. But you could achieve something similar by removing source line and to do something like this.

```r
pr <- plumb("main.R")
prf <- plumb("functions.R")
pr$mount("/functions/", prf)
pr$run()
```

What you can do right now is plumb each file to a different router and then add them on top of each other. No need for `source`.

See https://www.rplumber.io/docs/programmatic-usage.html#mount-static for documentation

Plumber starts by parsing the file you sent to the `plumb` method line by line to extract information about your endpoints. It then execute all lines it could not match with a known decoration (your source line in this case). `plumb` method only allows for one file to be parsed at a time. There is no reason why it could not just paste the content of multiple files together and then parse it but I think it would not look great? Anyway...

**Comment by michalskop** [comment]
Thanks @meztez !

For future reference:
It is also (apart of the previous reply) possible to create a new file (e.g. `api.R`) and put all the endpoints there( + name the functions in the _sourced_ files), e.g.:

api.R:
```R
# plumber.R

source("./main.R")

#* Echo back the input
#* @param msg The message to echo
#* @get /echo
function(msg) {
  main.echo(msg)
}

#* Return "hello world"
#* @get /hello
function(){
  functions.hello()
}

```

main.R:
```R
source("./functions.R")


test.echo = function(msg=""){
  list(msg = paste0("The message is: '", msg, "'"))
}

```

functions.R:
```R
functions.hello = function(){
  "hello world"
}

```
And then
```
pr = plumb("main.R")
pr$run()
```

And then both `/echo` and `/main` endpoints are accesible.

**Comment by meztez** [comment]
> `pr = plumb("main.R")`
should probably be something like for it to work
`pr = plumb("api.R")`
