### ISSUE TITLE
Error in normalizePath

### ISSUE THREAD

**Issue by datapicnic** [rstudio/plumber#538]
### normalizePath trying to create a DigitalOcean Droplet

Hi - I'm currently trying to set up my first DigitalOcean API - I'm running a windows 10, and just tried upgrading my R to 4.0.1 but I get the same result.  While it does actually create the droplet - I can't seem to plumb to it, otherwise the API plumbs fine see below:

```R
 id <- do_provision()
#If I still try to plumb to the droplet...
do_deploy_api("GrizzlyTraveler", "example", "C:/API", 9001, forward = FALSE,swagger = TRUE)
# I seem to get the below:
```
THIS ACTION COSTS YOU MONEY!
Provisioning a new server for which you will get a bill from DigitalOcean.
Using default ssh keys: myusername
NB: This costs $0.00744 / hour until you droplet_delete() it
Waiting for create ...............
New server key: 32:4c:eb:6f:45:3b:50:9a:2c:56:45:58:ee:6b:09:2
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="C:\Users\myusername\AppData\Local\Temp\Rtmpqi4P7C\file714844bb7c41": The system cannot find the file specified

> traceback()
7: normalizePath(to, mustWork = TRUE)
6: ssh::scp_download(session = session, files = remote, to = local, verbose = TRUE)
5: cat(ssh::scp_download(session = session, files = remote, to = local,verbose = TRUE), sep = "\n")
4: do_scp(droplet, local, remote, user, scp = "download", keyfile, sh_passwd, verbose = verbose)
3: analogsea::droplet_download(droplet, paste0("/tmp/", randName), tf)
2: droplet_capture(droplet, "swapon | grep \"/swapfile\" | wc -l")
1: do_provision()

# If i still try to plumb to the droplet:
> do_deploy_api("GrizzlyTraveler", "example", "C:/API", 9001, forward = FALSE,swagger = TRUE)
Error in FUN(X[[i]], ...) : File or directory does not exist: C:/API/**

**Comment by meztez** [comment]
It is hard to debug since it seems to be specific to your filesystem. The problem seems to originate from analogsea which is another package. It fails to copy files from your file system to the droplet.

File or directory does not exist: C:/API/**, thats a solid queue right there.

**Comment by datapicnic** [comment]
Thanks Meztez - I logged onto the droplet and it looked as though R hadn't been installed on it and the file hadn't gone across - I'll try to mess around with my OpenSSH - maybe it's not connecting right? analogsea seems to connect OK to my account but maybe I'll try a few other commands to see if they are working.  Thanks!

**Comment by kachergis** [comment]
FWIW I'm having the same issue right now on a Mac -- have tried both the CRAN and github versions of plumber.

**Comment by meztez** [comment]
@kachergis Could you provide more details? @datapicnic mentionned two errors above. One in normalizePath and one from do_deploy_api. Providing a lot of execution details help a lot when trying to pinpoint potential problems. Thanks you.

**Comment by meztez** [comment]
@kachergis, @datapicnic Could test this branch? 

```r
remotes::install_github("meztez/plumber", "digital_ocean")
```

It works on my Windows 10 machine, but I could not replicate the error you seem to be getting.

**Comment by kachergis** [comment]
Hi @meztez, thanks for your prompt response and sorry for not including more details (I was having the same normalizePath error). Following your suggested remote reinstalls, droplet_create succeeds but do_provision does not. Let me know if you need more details--thanks again!

> plumber::do_provision(droplet)
New server key: [xxx]
         2 /private/var/folders/9t/wnkqz64d1m1dgcxdw07dm9ph0000gp/T/RtmpEwEB3a/ouKhYjXPRH

`Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
no label, UUID=4953a93e-55a7-41c5-9c2a-20eb694a5a80
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.BVcp2FaYuJ/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
gpg: key 51716619E084DAB9: public key "Michael Rutter <marutter@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Error in droplet_ssh(droplet, "sudo apt-get update -qq", "sudo apt-get upgrade -y") : 
  argument "droplet" is missing, with no default`
> traceback()
5: as.droplet(droplet)
4: droplet_ssh(droplet, "sudo apt-get update -qq", "sudo apt-get upgrade -y")
3: analogsea::debian_apt_get_update()
2: install_new_r(droplet)
1: plumber::do_provision(droplet)

**Comment by meztez** [comment]
@kachergis That's an error on my. Can retry, I've added the missing parameter.

**Comment by kachergis** [comment]
This worked--thanks so much, @meztez !

**Comment by csearcy31** [comment]
@meztez I'm having roughly the same issue. When I use your branch of plumber (`meztez/plumber@digital_ocean`), I am able to successfully create the droplet, but the function `plumber::do_provision()` isn't installed, so I can't provision it. When I simply install meztez/plumber, I'm getting the following error, which I have also gotten from CRAN plumber:

`Error in if (utils::packageVersion("analogsea") < package_version(analogsea_version)) { : 
  argument is of length zero
`

Any idea what might be causing either of these issues?

**Comment by muschellij2** [comment]
Please see #642 and #643.  The `normalizePath` came from `ssh`, which assumes you're using a temporary **directory** to download files.  The old code of `plumber` at https://github.com/rstudio/plumber/blob/58e84ac477e8700c87e91458b3f437b5dd16b877/R/digital-ocean.R#L107 used `tempfile` (which by default does not exist), but now uses `tempdir()`, which does.  That fixes the normalizePath issue.  The issue @csearcy31 has is spaces in the package names, which #643 should fix.

**Comment by meztez** [comment]
@csearcy31 My branch will not be maintained, we are hoping to move all plumber deployment to another package. You should not rely on it and maybe only use it for testing/exploring.

**Comment by schloerke** [comment]
Don't have permissions to move the issue to `meztez/plumberDeploy`. So closing here and making a new issue in `meztez/plumberDeploy`. 

See https://github.com/meztez/plumberDeploy/issues/11
