### ISSUE TITLE
Remove PR/Issue number from News

### ISSUE THREAD

**Issue by schloerke** [rstudio/plumber#539]
By linking, it can cause CRAN to reject due to GitHub complaining about too many requests too quickly.

GitHub will auto link all PRs / Issues as necessary in release notes.

**Comment by meztez** [comment]
Good to know

**Comment by meztez** [comment]
Used regex:
`\[(#[0-9]+)\]\([^)]+\)` replace with `\1`

**Comment by meztez** [comment]
Done in #547
