### ISSUE TITLE
Uploading and receiving .RData files 

### ISSUE THREAD

**Issue by LJStroemsdoerfer** [rstudio/plumber#541]
Hey guys,

I need to use the `upload_file()` option in order to upload an .RData file to my plumber API. I am using the following call to do so:

```
"http://localhost:8000/post_endpoint" %>%
         httr::POST(.,
                            body = upload_file("model_list.RData")) %>%
         httr::content(.)
```

The API looks as follows:

```
#* @post /post_endpoint
post_endpoint <- function(req){

    file <- Rook::Multipart$parse(req)$req$tempfile
    model <- readRDS(file)
    
}
```

However, whenever I try to do so, I get warnings regarding the input and it seems that the file is corrupted and cannot be read.

```
Warning in if (stri_startswith_fixed(body, "{")) { :
  the condition has length > 1 and only the first element will be used
Warning in if (stri_startswith_fixed(qs, "?")) { :
  the condition has length > 1 and only the first element will be used
Warning in strsplit(qs, "&", fixed = TRUE) :
  input string 7 is invalid UTF-8
Warning in strsplit(qs, "&", fixed = TRUE) :
  input string 16 is invalid UTF-8
Warning in strsplit(qs, "&", fixed = TRUE) :
  input string 17 is invalid UTF-8
Warning in strsplit(qs, "&", fixed = TRUE) :
  input string 18 is invalid UTF-8
Warning in strsplit(qs, "&", fixed = TRUE) :
  input string 22 is invalid UTF-8
<simpleError in readRDS(file): bad 'file' argument>
```

Is it in general possible to upload and handle .RData files or is there another preferred file type? I am using .RData as the file contains a model object.

**Comment by meztez** [comment]
Maybe
`Rook::Multipart$parse(req$rook.input)$req$tempfile`

**Comment by LJStroemsdoerfer** [comment]
Thank you very much for the suggestion. Unfortunately it does not work `Rook::Multipart$parse(req$rook.input)$req$tempfile`does not work either. I found some examples working just fine for .csv and .xlsx files. However, .RData files seem to be handled a bit differently.

**Comment by meztez** [comment]
There a current PR that should introduce this functionality to plumber, let me come back with an example if it gets merged into master.

Otherwise you are close, I suggest you use a `browser()` statement before your `file <-` assignment statement. You can then test it out in debug mode.

**Comment by meztez** [comment]
From your code, using `httr`, the request content-type should be "application/octet-stream".

That means you directly use the raw bytes. This is not a multipart body.

You first `rewind` to to make sure the seek position is back at the beginning of the body.
The you can use the `read` method to get the raw bytes and write them to a temp file.
You can then read from that temp file.
I'm sure there is some way to bypass the whole save to disk part, but I can not remember at the moment.

```r
#* @post /post_endpoint
post_endpoint <- function(req){
  browser()
  f <- tempfile()
  req$rook.input$rewind()
  writeBin(req$rook.input$read(), f, useBytes = TRUE)
  model <- readRDS(f)
}
```

**Comment by LJStroemsdoerfer** [comment]
Nice, that last example worked for the .RData files. Thank you very much for the help and the effort :)
