### ISSUE TITLE
Cookie test

### ISSUE THREAD

**Issue by meztez** [rstudio/plumber#544]
Just a note to check cookies test, seems there can be a fail when cookie created between two time

```r
 ── 1. Failure: cookies can convert to string (@test-cookies.R#66)  ─────────────
cookieToStr("abc", 123, expiration = expiresSec) not equal to paste0("abc=123; Expires= ", expyStr, "; Max-Age= ", expiresSec).
1/1 mismatches
x[1]: "abc=123; Expires= Fri, 12 Jun 2020 20:26:10 GMT; Max-Age= 10"
y[1]: "abc=123; Expires= Fri, 12 Jun 2020 20:26:09 GMT; Max-Age= 10"
```

**Comment by schloerke** [comment]
Which operating system / R version?

**Comment by meztez** [comment]
https://github.com/rstudio/plumber/runs/766754031?check_suite_focus=true

macOS latest devel (first)

**Comment by meztez** [comment]
It seems there is already a TODO in test-cookies.R, closing since already aware.
