### ISSUE TITLE
Either define or remove ... in parse_*(...)

### ISSUE THREAD

**Issue by cpsievert** [rstudio/plumber#559]
Currently they aren't being used anywhere...are they even useful?

**Comment by meztez** [comment]
The ones in parse_* serve no purpose so far, the ones in the sub function are sometimes used when multiple headers are set on request and returned by parse_multipart.

I removed the first one in the yaml support branch.

**Comment by meztez** [comment]
removed, merged in #556

**Comment by schloerke** [comment]
Thank you!
