### ISSUE TITLE
swagger not working with RStudio Pro (https)

### ISSUE THREAD

**Issue by bczernecki** [rstudio/plumber#569]
I am trying to run a demo plumber code with RStudio Pro. API service starts properly, but when I click on Execute button I get error code 404 as shown on the screen below:

![screen1](https://user-images.githubusercontent.com/8086055/85837540-6f64a400-b798-11ea-8254-c72d1df03ce4.png)

I found a workaround which is based on adding one more time information about my session in the swagger's window

`https://r-mydomain.com/s/596fccfc78a319ca49dce/p/dfe61e8c/swagger.json?schemes=https&host=r-mydomain.com&path=/s/596fccfc78a319ca49dce/s/596fccfc78a319ca49dce/p/dfe61e8c/`

which is then forwarded and visible in the Base URL part:

![screen2](https://user-images.githubusercontent.com/8086055/85846802-b063b500-b7a6-11ea-9389-6b814863a219.png)

... and then everything works like a charm.

Is there any way to add this information  (about session?) to the "Explore" swagger form/URL while launching plumber API service?  
BTW., I tried the same with the non-commercial RStudio Server and it works without any problems. Any hints what might be wrong are highly appreciated.

### System details

```
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Red Hat Enterprise Linux    
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 date     2020-06-26                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [2] CRAN (R 3.5.3)
 cli           1.1.0   2019-03-19 [2] CRAN (R 3.5.3)
 crayon        1.3.4   2017-09-16 [2] CRAN (R 3.5.3)
 httpuv        1.5.2   2019-09-11 [2] CRAN (R 3.5.3)
 jsonlite      1.6     2018-12-07 [2] CRAN (R 3.5.3)
 later         1.0.0   2019-10-04 [2] CRAN (R 3.5.3)
 magrittr      1.5     2014-11-22 [2] CRAN (R 3.5.3)
 plumber     * 0.4.6   2018-06-05 [1] CRAN (R 3.5.3)
 promises      1.1.0   2019-10-04 [2] CRAN (R 3.5.3)
 R6            2.4.0   2019-02-14 [2] CRAN (R 3.5.3)
 Rcpp          1.0.2   2019-07-25 [2] CRAN (R 3.5.3)
 rsconnect     0.8.15  2019-07-22 [2] CRAN (R 3.5.3)
 rstudioapi    0.10    2019-03-19 [2] CRAN (R 3.5.3)
 sessioninfo   1.1.1   2018-11-05 [2] CRAN (R 3.5.3)
 stringi       1.4.3   2019-03-12 [2] CRAN (R 3.5.3)
 withr         2.1.2   2018-03-15 [2] CRAN (R 3.5.3)
```

**Comment by meztez** [comment]
Can you validate if you still get the error with development version?

Thank you

**Comment by bczernecki** [comment]
@meztez - yes, that was it! Thank you for the help!

**Comment by schloerke** [comment]
@bczernecki Thank you for checking!
