### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by peter279k** [rstudio/plumber#580]
After looking at this [page](https://www.rplumber.io/docs/quickstart.html#specifying-the-inputs), I found following sections are not found:

- `1 Introduction` https://www.rplumber.io/docs/index.html
- `1.1 Web APIs` https://www.rplumber.io/docs/index.html#web-apis
- `1.2 Installation` https://www.rplumber.io/docs/index.html#installation
- `4 Rendering Output` https://www.rplumber.io/docs/rendering-and-output.html
- `4.1 The Response Object` https://www.rplumber.io/docs/rendering-and-output.html#response-object
- `4.2  Serializers` https://www.rplumber.io/docs/rendering-and-output.html#serializers
- `4.3 Error Handling` https://www.rplumber.io/docs/rendering-and-output.html#error-handling
- `4.4 Custom Serializers` https://www.rplumber.io/docs/rendering-and-output.html#custom-serializers
- `4.5 Setting Cookies` https://www.rplumber.io/docs/rendering-and-output.html#setting-cookies
- `9 Tips and Ticks` https://www.rplumber.io/docs/tips-tricks.html
- `9.1 Debugging` https://www.rplumber.io/docs/tips-tricks.html#debugging
- `9.2 Testing` https://www.rplumber.io/docs/tips-tricks.html#testing
- `9.3 Organizing Large Applications` https://www.rplumber.io/docs/tips-tricks.html#organizing-large-applications
- `9.4 Swagger` https://www.rplumber.io/docs/tips-tricks.html#swagger
- `9.5 Performance` https://www.rplumber.io/docs/tips-tricks.html#performance
- `Appendix B.  Plumber 0.4.0 Migration Guide` https://www.rplumber.io/docs/plumber-0-4-0-migration-guide.html
- `Appendix C. Citations` https://www.rplumber.io/docs/citations.html
- `GitHub WebHook` https://www.rplumber.io/examples/github
- `Receive Emails (mailgun)` https://www.rplumber.io/examples/mailgun

![image](https://user-images.githubusercontent.com/9021747/86357437-6a27bd80-bca0-11ea-87f6-889511bf17c4.png)

![image](https://user-images.githubusercontent.com/9021747/86358310-d656f100-bca1-11ea-85a5-eb65bbff5dc1.png)

![image](https://user-images.githubusercontent.com/9021747/86358362-ec64b180-bca1-11ea-82d7-9b2eb1187da4.png)

![image](https://user-images.githubusercontent.com/9021747/86357351-4a909500-bca0-11ea-9cd7-02bcf9be191f.png)

I think these above links are changed and the doc should be updated.

**Comment by meztez** [comment]
Thank you for reporting this. The plumber documentation is currently being worked on as the package itself.
See PR #570. Once things settle, the documentation itself should reflect the current state of the package.
