### ISSUE TITLE
Port existing `analogsea` / digital ocean code to a new `plumberDigitialOcean` R package

### ISSUE THREAD

**Issue by schloerke** [rstudio/plumber#593]
The code on CRAN has been broken for at least 6 months.  Plumber can not update as fast as `analogsea` might want to update. 

This code was originally set up for showing how a toy example of plumber can be deployed to Digital Ocean.  However, this adds extra dependencies and is out of scope for the `plumber` R package.

I propose that 
* `plumber` Digital Ocean code be ported to an external R package (`plumberDigitalOcean`?). It could then be used in the `plumber` documentation on how to host on Digital Ocean.  
* The existing plumber functions should not really exist in outside scripts, so they may be gutted to proved a single message of `"Please visit USER/plumberDigitalOcean to run FUNC()"`. 
  * Maybe paired with message `remotes::install_github("USER/plumberDigitalOcean"); plumberDigitalOcean::FUNC()`

------------------

I would welcome this breaking change.

**Comment by meztez** [comment]
And the answer to that is... yes.

I would even go as far as calling the new package plumberDeployment or something like that and support multiple deployment models.

**Comment by schloerke** [comment]
I like the name `plumberDeployment`!

... want to take a run at it, @meztez ? (My plate is starting to fill up with `rstudio/learnr`.)

**Comment by meztez** [comment]
yes yes, sometimes end of week or next week.

**Comment by blairj09** [comment]
I'm happy to be involved here as well! Although I'll be mostly unavailable for the next month+ 👶 🎉
