### ISSUE TITLE
Bypassing serialization example fails with current GH build

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#597]
The [bypassing serialization example](https://www.rplumber.io/articles/rendering-output.html#bypassing-serialization) returns a 500 error on the current GH build of the package. The same error doesn't occur with the CRAN release.

```r
#* Endpoint that bypasses serialization
#* @get /foo
function(res){
  res$body <- "Literal text here!"
  
  res
}
```

![image](https://user-images.githubusercontent.com/10444878/87831302-61a6b980-c840-11ea-9303-13895e0298c0.png)

**Comment by schloerke** [comment]
I believe this is related / the root cause: https://github.com/rstudio/httpuv/issues/195

**Comment by schloerke** [comment]
Closing as this issue should be fixed by httpuv
