### ISSUE TITLE
Hex logo in new project dialogue

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#614]
Replace the Plumber graphic in the new project dialogue with the updated hex logo:
![image](https://user-images.githubusercontent.com/10444878/88103515-5c0de400-cb5e-11ea-92d2-e91a330bfa99.png)

**Comment by meztez** [comment]
New project dialog is ok, new file dialog still has the old logo, probably an rstudio issue/PR

**Comment by schloerke** [comment]
Resolved
