### ISSUE TITLE
Plumber comments should be evaluated in the correct environment

### ISSUE THREAD

**Issue by jcheng5** [rstudio/plumber#619]
This should work:

```r
foo <- TRUE
#' @serializer json list(simplifyVector=foo)
...
```

```r
bar <- list(simplifyVector=TRUE)
#' @serializer json bar
...
```

**Comment by meztez** [comment]
Good catch, let me check

**Comment by jcheng5** [comment]
(Sorry for being so terse, I filed this during a live code review with @schloerke)

**Comment by Seebacherca** [comment]
Wonderful information about plumber, thanks a lot for sharing kind of content with us. Your blog gives the best and the most interesting information. I wonder if we can gather such practical information about it, a great post definitely to come across.
**[North Vancouver Furnace Repair](https://seebacher.ca/)**
