### ISSUE TITLE
XML Output instead of JSON

### ISSUE THREAD

**Issue by changboon** [rstudio/plumber#65]
Hi,

I have formatted the output in XML and like to return the output as XML instead of JSON.

plumber now defaults to JSON. Is there any way to do that?

**Comment by trestletech** [comment]
Hi there. Thanks for opening this ticket.

I haven't implemented XML support just yet because I'm not sure how it should be implemented. How do you want it to behave?

e.g. if your plumber function returns a list like `list(a=1, b=2)` what would you want the resultant XML doc to look like?

**Comment by aleDsz** [comment]
I think that he want to return XML to use in Excel or something.

**Comment by schloerke** [comment]
In v1.0.0, serializers can be registered using `register_serializer()`.  In the serialization function, you can format the value as necessary and wrap it with a `serializer_content_type()` to set the appropriate header values.

A good example for inspiration: https://github.com/rstudio/plumber/blob/b5cb8d20d9959810a10690a8c2c922b1d95919f5/R/serializer.R#L183-L193
