### ISSUE TITLE
Error building docker with plumber

### ISSUE THREAD

**Issue by datahack336** [rstudio/plumber#671]
I have a docker file that works for year now. It did not have any issues, but today when I tried to build it, I've got following error:

dependency 'sodium' is not available for package 'plumber'

This was the command I've tried to execute:

`RUN R -e "install.packages(c('plumber'), repos='https://cloud.r-project.org')"`

Base image is ubuntu:19.10

Another error I found - "dependency 'sodium' is not available for package 'plumber'"

**Comment by meztez** [comment]
Plumber now requires a package that requires libsodium to be installed on your system.

In your docket file
```
RUN apt install libsodium-dev
```

**Comment by datahack336** [comment]
Thank you!
