### ISSUE TITLE
Prettify Response

### ISSUE THREAD

**Issue by jdonnell01** [rstudio/plumber#673]
Hello,

Is it possible to prettify the data that is exposed via R plumber?
For instance, when the data is viewed via the endpoint the exposed data is very difficult to read for some end users that sometimes view the data in a browser.

Thank you

**Comment by schloerke** [comment]
Assuming you have a json serializer (default serializer), add (or update) this line to your route:

```r
#' @serializer json list(pretty = TRUE)
```

**Comment by jdonnell01** [comment]
Thank you for the quick reply. I have jsonlite installed which as I understand is what plumber uses out of the box to convert dataframes to json objects. Is this what you are referring to? 

I included the above, however I received the error: 
`Error in (function ()   : unused argument (pretty = TRUE)`

**Comment by schloerke** [comment]
Correct. Plumber uses jsonlite under the hood via plumber::serialize_json() ￼

Please update to plumber v1.0.0 and try again.

**Comment by jdonnell01** [comment]
Thank you. I updated to v1.0.0, however now when I try to run I get the error:

`Error: 'is_present' is not an exported object from 'namespace:lifecycle'`

**Comment by schloerke** [comment]
Dang. I guess I need a min version of lifecycle v0.2.0

Mind updating the lifecycle package?

**Comment by jdonnell01** [comment]
Thank you very much. This seems to be working now.
Only issue is that with the new package (v 1.0.0) it seems that no CSS is applied to the __docs__ page so it is difficult to navigate.

Is this a known issue?

**Comment by schloerke** [comment]
Mind viewing the docs url in a _incognito window_? This will bust any browser cache that the css might be using.

**Comment by jdonnell01** [comment]
Hmm, that didn't seem to help. I looked in the console and there are 404 responses for the following:

swagger-ui-bundle.js.map
swagger-ui-standalone-preset.js.map
swagger-ui-css.map

**Comment by schloerke** [comment]
Missing map files (which I removed in `swagger` to meet package size guidelines) should not cause a general css rendering issue. Those map files can only be found from the source file. So the source files are being found.  

Do you mind taking a screen shot of the _broken_ docs in chrome? And the inspector's network window? 
I developed using macOS chrome, so I did not run into this issue.

**Comment by jdonnell01** [comment]
For some reason Github errors out when I try to upload the image. This is what I see in Dev Tools as Warnings:

DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8000/__docs__/swagger-ui.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8000/__docs__/swagger-ui-bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8000/__docs__/swagger-ui-standalone-preset.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by jdonnell01** [comment]
Hello,

Were you able to recreate this issue locally?
Thank you for the continued help here.

**Comment by schloerke** [comment]
No. Can you try attaching screen shots? There are a lot of ways for css to fail, but it doesn't make sense since the `swagger-ui.css` is returning.

Also worth a try... can you restart your computer and try again? ...trying to think of ways to bust Chrome's cache.

**Comment by jdonnell01** [comment]
I restarted my computer but the issue still remains. Here are some screenshots:

![image](https://user-images.githubusercontent.com/26280479/93726974-ee465e80-fb86-11ea-90c0-1a2692427c4c.png)
![image](https://user-images.githubusercontent.com/26280479/93726985-f7cfc680-fb86-11ea-84c5-a3b345878b92.png)

**Comment by meztez** [comment]
Do you mind sharing your plumber API script. I'm unable to reproduce on windows.

**Comment by jdonnell01** [comment]
Thanks for the continued help.
Here is my current environment as well as my script:.

Also, please let me know if there is a more efficient way other than Shiny's invalidateLater to continually fetch updated datasets.

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.6.1 shiny_1.3.2    dplyr_0.8.3    plumber_1.0.0 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       rstudioapi_0.11  magrittr_1.5     webutils_1.1     tidyselect_0.2.5 xtable_1.8-4     R6_2.4.0        
 [8] rlang_0.4.5      tools_3.5.0      htmltools_0.4.0  yaml_2.2.0       assertthat_0.2.1 digest_0.6.25    tibble_2.1.3    
[15] lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.3      later_0.8.0      promises_1.1.1   glue_1.3.1       mime_0.7        
[22] stringi_1.4.3    compiler_3.5.0   swagger_3.33.0   pillar_1.4.2     httpuv_1.5.2     pkgconfig_2.0.2 
```

```
library(plumber)
library(dplyr)
library(shiny)
library(jsonlite)

data_path <- "***localdirectorypath***"

opendata <- function(dataset) {
  assign(as.character((substitute(dataset))),
         try(
           readRDS(file = paste0(data_path, deparse((substitute(dataset))), ".rds")), silent = TRUE), envir = globalenv())
}

fetchdata <- function() {
  opendata(dataset1)
  opendata(dataset2)
  print("Data Has Been Fetched")
}

fetchdata()

observe({
  invalidateLater(21600000) #Refresh Every 12 Hours
  fetchdata()
})

#* @filter cors
cors <- function(res) {
  res$setHeader("Access-Control-Allow-Origin", "*")
  res$setHeader("content-type", "application/json")
  plumber::forward()
}

#* @serializer json list(pretty = TRUE)
#* @get /leftHandNav
function(req) {
  
  fromJSON(toJSON(c(list(dataset_1 = dataset1),
  list(dataset_2 = dataset2)), auto_unbox = TRUE))
  
}
```

**Comment by meztez** [comment]
I'm able to reproduce.

**Comment by meztez** [comment]
So that was an easy fix.

Remove this line in your filter, you are telling plumber to return everything with an application/json content-type header. Even the css. That is why it is not parsed by the browser. Content-type will be set by your route serializer.
```R
  res$setHeader("content-type", "application/json")
```

**Comment by jdonnell01** [comment]
Ah, thank you!
I should have seen that!
