### ISSUE TITLE
Please Add File Upload Feature for Swagger Documentation Page and Tag

### ISSUE THREAD

**Issue by KlausPuchner** [rstudio/plumber#675]
First thank you for this great package and keep up the great work! 👍 What we especially love is the Plumber/Swagger API documentation, that also allows end users without advanced technical skills to try out the API.

We built a computer vision microservice with plumber (you hand over an image to the API and the model delivers/shows the input image with bounding boxes around recognized objects).

In terms of user acceptance it is very important to us that potential consumers of the API can play around with it a little before adopting it into their solution.

Therefore it would be great to have a tag (e.g. @fileupload) which enables Plumber to generate a file upload section in the Swagger Documentation page for file upload purposes.

We know it is possible to send files (in my special case jpegs) to the API via curl - but unfortunately this is only an adequate way for developers but not for technically unexperienced users (which can be essential in terms of solution acceptance testing).

I hope I could explain my feature request in a proper way - if not, please let me know. :)

**Comment by meztez** [comment]
This is already available via 

@param param_name:file

**Comment by meztez** [comment]
I could not fund anything in the doc that describe how plumber parse the `#* @param` decorator.

Syntax should be

```R
#* @param {parameter name}:{parameter plumber type}*? {Parameter description}

# Examples
#* @param a:file* A required jpeg file
#* @param a_multi:[file] An array of jpeg files
#* @param b:df A dataframe
```

{parameter name} is matched with parameter name used in your plumber expression (function below decoration) signature.
{parameter plumber type} can be any of the following : bool, boolean and logical; dbl, double, float, number and numeric; int, and integer; chr, str, character and string; list, data.frame, df and object; file and binary. All synonyms produce the same OpenApi Type.

You can wrap any {parameter plumber type} inside square brackets [] to turn them into a variable length input array.

If you put an * after {parameter plumber type} (outside square brackets). It means the particular parameter is required by your API.

Description is mostly for documentation purpose.

**Comment by KlausPuchner** [comment]
Thanks for your quick (and very helpful) reply. Your solution works like a charm. 🥇
