### ISSUE TITLE
Can't pass `envir` to `Plumber$handle()`

### ISSUE THREAD

**Issue by TylerGrantSmith** [rstudio/plumber#676]
Attempting to pass an environment through the `envir` arg of `Plumber$handle()` results in an error.  Is it not possible to use different enclosing environments for different endpoints?  

The current method forces the use of the `private$envir` of the router without checking if an alternative has been provided by the user.

https://github.com/rstudio/plumber/blob/c051c6b6940c3887992caf9be925d551956271d9/R/plumber.R#L357

``` r
library(plumber)

pr <- Plumber$new()
pr$handle("GET","/foo", function() "bar", envir = new.env())
#> Error in make_parser(parsers): is.list(aliases) is not TRUE
```

<sup>Created on 2020-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by meztez** [comment]
Thats a funky one, let me come back to you.

**Comment by TylerGrantSmith** [comment]
The error is caused because `PlumberEndpoint$new` is being passed arguments by position, and when the named `envir` argument gets passed in via the `...`, the `private$envir`, `serializer` and `parsers` parameters get shifted one spot.  So the serializer function is assigned to `parsers` in the endpoints `initialization` function, which isn't a list causing `make_parser` to error.

**Comment by meztez** [comment]
Yes it not possible at the moment to use different environment per handle on the same router. But, you could mount routers on top of each other to have a different environment per router if that makes senses. I came to the same conclusion as you, I will let @schloerke respond if this is something plumber wants to support.

```R
?pr_mount
```

**Comment by TylerGrantSmith** [comment]
So I think really the question is whether or not all endpoints handled by a router must share the same enclosing environment or not.  If they must, then it seems like the `handle` method should error if you try to pass one in by name and the documentation should make that exception clear.  Otherwise, `handle` should check for a passed `envir` argument and default to `private$envir` if missing, as is done for `serializer` and `parsers`

**Comment by TylerGrantSmith** [comment]
Thanks @meztez I think that is fine.  My current project actually doesn't require the differing environments, but I thought that i could pass it with the endpoint definition rather than the router definition, which led to the error.

**Comment by schloerke** [comment]
I acknowledge the error. Not having named arguments is the root cause. We'll adjust #677 accordingly

On the flip side, if you're passing in a function to `handler`, `envir` is not used. The environment of the `handler` function has precedence and `envir` will be dropped. 

(...I wish I could remove the `envir` argument and only allow for `handler` to be a function. Maybe v2...)

**Comment by schloerke** [comment]
Looking at it some more, I don't think users should have the option of using `envir` within `Plumber$handle()`.

Two situations can occur:
1. Users pass in a function to `pr$handle(handle)`. `envir` is not used.
2. Users pass in an expression to `pr$handle(handle)`. `envir` is used to evaluate the expression. The `pr` object has context and should always be available. If the user wants to have a specific environment, they can create a function to be passed into `handle`.

#677 has been updated to throw if `envir` is passed in and to use named arguments when creating a new `PlumberEndpoint`.
