### ISSUE TITLE
All Annotations Appendix

### ISSUE THREAD

**Issue by meztez** [rstudio/plumber#678]
I could swear we had an all annotation appendix in the documentation. For the life of me I cannot find it. Can I rewrite one?

**Comment by schloerke** [comment]
I'd be happy for any documentation. I don't think we had one... only maybe in code.

**Comment by schloerke** [comment]
Historical: https://github.com/rstudio/apis-plumber/blob/8474a1019aca578b3d5ccbde9c1961505f68cab3/99-appendix-a.Rmd#L4 (...which shows nothing)

Related: https://github.com/rstudio/plumber/issues/321

**Comment by meztez** [comment]
I'm already working on one, as a lot of the new features are not properly documented, which is a shame since they are so cool.
