### ISSUE TITLE
Support OpenAPI Spec Files

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#692]
Version 1.0.0 introduced a new way to modify the API UI via `pr_set_api_spec()`. This function accepts either a list object defining the spec or a function that modifies the existing spec and returns it. However, if the API spec is defined externally, there's no good way to provide it without serializing it into a list first.

For example, if I have a file `openapi.yml`:
```yaml
servers:
  - url: ''
openapi: 3.0.3
info:
  description: API Description
  title: Foo
  version: 1.0.0
paths:
  /health-check:
    get:
      summary: ' Determine if the API is running and listening as expected'
      responses:
        default:
          description: Default response.
      parameters: []
```

And I want to use that to define my API UI, currently, I need to do something like the following:
```r
pr %>%
  pr_set_api_spec(yaml::read_yaml("openapi.yaml"))
```

But this feels a bit odd since I'm serializing the spec file into a list, just so it can be turned back into a spec file. It would be nice if I could specify a file path to the spec file:

```r
pr %>%
  pr_set_api_spec("openapi.yaml")
```

**Comment by meztez** [comment]
@blairj09 Should it supports URL too, or just local files?

**Comment by blairj09** [comment]
URL support would be nice, and I don't see a reason to exclude it

**Comment by meztez** [comment]
I initially had it in, changes suggested limited support to local files only. Maybe check with @schloerke.
