### ISSUE TITLE
@plumber tag should verify that the returned router matches the supplied router

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#707]
The `@plumber` tag was introduced to enable increased flexibility while defining routers in the traditional Plumber style with tags. It's expected that it's used as follows:

```r
#* @plumber
function(pr) {
  # Modify and return pr
}
```

However, it's easy to accidentally do the following:
```r
#* @plumber
function(pr) {
  pr() %>%
    pr_get()
}
```

In this case, the supplied router isn't modified, but instead a new router is created. This leads to unexpected end results when the router is fully assembled. It would be helpful if Plumber verified that the output of a `@plumber` function was indeed a modification of the input instead of the instantiation of an entirely new router.

**Comment by meztez** [comment]
Just to be clear, the newly created router is not replacing router from function argument. It just does nothing with it. You do not need to return the router itself has it is an environment and is modified in place.

There is multiple reasons why you would to create a newly router inside this block. Mounting router on top of each other, Adding static assets. There is also use case were you would not want to modify the router and still use this block.

I'm not convinced this leads to unexpected end results.

See where this expression is evaluated
https://github.com/rstudio/plumber/blob/ab050455327e0b52d36a3a0925b1b021e6743348/R/plumb-block.R#L307

**Comment by blairj09** [comment]
All good points. I think what I'm trying to get after is a way to prevent people from shooting themselves in the foot by trying something like the following:
```r
#* @get /foo
function() "foo"

#* @plumber
function(pr) {
  pr() %>%
    pr_get("/bar", function() "bar")
}
```

And then expecting both `/foo` and `/bar` to exist on the router, when only `/foo` will exist, since the `@plumber` tag never actually modifies the router.

Maybe this is a non-issue, but it's tripped me up multiple times already.

**Comment by schloerke** [comment]
Don't know if it'd be useful to check if `pr` has not been updated and display a warning. 

If users just want to run code, it is not necessary to do this in a `@plumber` block. They can do that where ever. 

I'd rather not have an _updated_ flag. It is too error prone / I'll forget a method eventually. Maybe we could check this by `pr$clone()`ing before and comparing after executing the `@plumber` block? The **before** and **after** values _should_ be different.

**Comment by meztez** [comment]
> If users just want to run code, it is not necessary to do this in a @plumber block. They can do that where ever.

Sometimes you do need it since you want access to the pr object, say to read the spec, list routes, or do any other actions on the actual router object without modifying it.

Instead of looking at the object. We could check the actual code when plumbing to issue warning?

> I saw you used a function with pr argument but it isn't used in the plumber block. Maybe you used pr() instead?

But I don't like assuming user is maybe wrong.

**Comment by meztez** [comment]
```R
if (!any(grepl(paste0(regex,formals(expr),regex), lines))) then #issue warning
```
 Something like that

**Comment by schloerke** [comment]
Dang. Forgot about a valid "just read" situation. 

--------------------------

What about checking for "if a router is returned, it should match the original router"?

Ex: 

```r
# good. (not a Plumber object)
#* @plumber
function(pr) { 42 }
#* @plumber
function(pr) { "not a router" }

# good. is original
#* @plumber
function(pr) { pr }
#* @plumber
function(pr) { 
	x <- pr()
	pr %>% 
		pr_mount("/x", x)
}

# should produce a warning as original `pr` is not returned
#* @plumber
function(pr) { 
	pr()
}
#* @plumber
function(pr) { 
	x <- pr()
	pr %>% 
		pr_mount("/x", x)
    x
}
```

**Comment by schloerke** [comment]
I'd rather not inspect user code if we can avoid it. It is more much trouble than it is worth. 

Inspecting unevaluated user code usually runs into problems quickly.

**Comment by meztez** [comment]
Ok, check if return class is a plumberRouter, if yes, make sure it is the same then the one in the argument.

**Comment by schloerke** [comment]
Random idea... Don't know if each router should get random ID at creation time. This could also be leveraged within the recursive printing PR.

**Comment by schloerke** [comment]
^^ This might cause serialization issues. 

Maybe we have a slot, but don't fill it in until checking is necessary. After checking, clear it out.
