### ISSUE TITLE
How to install plumber 1.0.0.9999 Development version?

### ISSUE THREAD

**Issue by kwon14** [rstudio/plumber#713]
Hi. thank for your excellent work!!

I would like to ask..

How to install plumber 1.0.0.9999 Development version?

Thank U.!!

The issue tracker is not for questions. If you have a question, please feel free to ask plumber help questions on RStudio Community under the `plumber` tag, at https://community.rstudio.com/tag/plumber.  Please tag your post with a `plumber` tag to increase visibility.

[Click here](https://community.rstudio.com/new-topic?title=&tags=plumber&u=barret&body=%0A%0A%0A--------%0A%0A%3Csup%3EReferred%20here%20by%20%5B%60rstudio%2Fplumber%60%5D(http%3A%2F%2Fgithub.com%2Frstudio%2Fplumber)%3C%2Fsup%3E%0A) to create a new post with a `plumber` tag.

**Comment by meztez** [comment]
From the README

https://github.com/rstudio/plumber#installation

**Comment by kwon14** [comment]
I used below install code that you can see ERROR code..
-------------------------------------------------------------
ARG PLUMBER_REF=master
RUN Rscript -e "remotes::install_github('rstudio/plumber@${PLUMBER_REF}')"

-------------------------------------------------------------
The downloaded source packages are in
        ‘/tmp/RtmpDvFEJl/downloaded_packages’
✔  checking for file ‘/tmp/RtmpDvFEJl/remotes763dcc3c6/rstudio-plumber-c39ae52/DESCRIPTION’ ...
─  preparing ‘plumber’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘plumber’ ...
   ** using staged installation
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
     namespace ‘webutils’ 1.0 is being loaded, but >= 1.1 is required
   Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
   Execution halted
   ERROR: lazy loading failed for package ‘plumber’
─  removing ‘/tmp/RtmppUT4Ek/Rinst1812d28595b/plumber’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'plumber' from GitHub:
  System command error, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
E>   namespace ‘webutils’ 1.0 is being loaded, but >= 1.1 is required
E> Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
E> Execution halted
E> ERROR: lazy loading failed for package ‘plumber’
E> * removing ‘/tmp/RtmppUT4Ek/Rinst1812d28595b/plumber’
E>       -----------------------------------
E> ERROR: package installation failed
Execution halted
The command '/bin/sh -c Rscript -e "remotes::install_github('rstudio/plumber@${PLUMBER_REF}')"' returned a non-zero code: 1

**Comment by meztez** [comment]
E> namespace ‘webutils’ 1.0 is being loaded, but >= 1.1 is required

It seems you have to update a dependency.
https://cran.r-project.org/web/packages/webutils/index.html
```
install.packages("webutils")
```

Read the error, it usually tells you want you need to do.

**Comment by kwon14** [comment]
I solved it like this.
Thank you so much for your help.
----------------------------------
RUN R -q -e "install.packages('webutils', version='1.1', repos='https://cran.r-project.org/')"
RUN R -q -e "install.packages('lifecycle', version='0.2.0', repos='https://cran.r-project.org/')"
RUN R -q -e "install.packages('swagger', version='3.33.1', repos='https://cran.r-project.org/')"

ARG PLUMBER_REF=master
RUN Rscript -e "remotes::install_github('rstudio/plumber@${PLUMBER_REF}')"
