### ISSUE TITLE
tryCatch inside plumber function

### ISSUE THREAD

**Issue by MislavSag** [rstudio/plumber#714]
I would like to use tryCatch inside plumber function
```R
function(
x <- tryCatch('s' + 1, error = function(e) print(e))
return(x)
)
```
### Describe the problem in detail
When I include `tryCatch` inside my plumber function it doesn't return the error message. but an empty list.

I would like to return an error message so I can debug the function more easily.

**Comment by meztez** [comment]
Plumber already run your function in a tryCatch, activate DEBUG mode on your router to get more than a 500: Internal error.

https://www.rplumber.io/reference/pr_set_debug.html
https://www.rplumber.io/reference/Plumber.html#arguments

**Comment by MislavSag** [comment]
I don't what I have done (tried several options), but now it is working. It returns an error message from an R function if it appears.

Tnx. Can be closed. I will reopen if necessary.

**Comment by meztez** [comment]
@MislavSag you can close it 👍 .
If you have a similar question in the future, please use https://community.rstudio.com/tag/plumber
You will have more visibility there. This issue tracker is mostly read by the plumber package developers.

> The issue tracker is not for general help questions -- please ask general plumber help questions on RStudio Community, https://community.rstudio.com/tag/plumber.

**Comment by Harry81622** [comment]
When planting trees and shrubs, be aware of the location of your sewer lines and choose species with less invasive root systems. This can prevent roots from growing into and damaging your pipes. [check these guys out](https://www.ecoplumbinghvac.com/)
