### ISSUE TITLE
Broken plumber deployments for existing Docker builds - Error in parse(file, keep.source = TRUE, srcfile = src, encoding = enc) :    R:1:1: unexpected input

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rstudio/plumber#731]
Hello, I'm getting some errors with older Docker files that do not now deploy with strange bugs I can't track down.

I see similar to https://github.com/rstudio/plumber/issues/373

My old Docker file:

```

FROM gcr.io/gcer-public/googlecloudrunner:master
COPY ["./", "./"]
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(rev(commandArgs()[1])); pr$run(host='0.0.0.0', port=as.numeric(Sys.getenv('PORT')), swagger=TRUE)"]
CMD ["api.R"]
```

`gcr.io/gcer-public/googlecloudrunner:master` has plumber installed on it.

From a couple of months ago it started erroring on launch of the container with

```
Error in parse(file, keep.source = TRUE, srcfile = src, encoding = enc) :   
R:1:1: unexpected input  
 1:   
     ^  
 In addition: Warning messages:  
 1: In readLines(file, warn = FALSE) :  
   invalid input found on input connection 'R'  
 2: In readLines(file, warn = FALSE) :  
   invalid input found on input connection 'R'  
 Error in parseUTF8(file) : Error sourcing R  
 Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> parseUTF8  
 Execution halted  
```

I think its not finding the "api.R" file anymore?  But from trying some debugging it looks like the ENTRYPOINT/CMD line is not finding R?

Anyhow from the suggestion in the issue above (https://github.com/rstudio/plumber/issues/373) I put the server launch in a separate R file and launched via Rscript - that worked:

```r
# server.r
pr <- plumber::plumb("api.R")
pr$run(host='0.0.0.0', port=as.numeric(Sys.getenv('PORT')), swagger=TRUE)
```

```
FROM gcr.io/gcer-public/googlecloudrunner:master
COPY ["./", "./"]
ENTRYPOINT ["Rscript", "server.R"]
```

I'd like to understand why it worked, and why the old one stopped working.

**Comment by meztez** [comment]
`rev(commandArgs()[1])` yield `"/usr/lib/R/bin/exec/R"`

`rev(commandArgs())[1]` yield `"api.R"`

Could it be a misplaced parenthesis?

**Comment by MarkEdmondson1234** [comment]
Ah ha! Thanks :)
