### ISSUE TITLE
Maybe support Chinese character in req$PATH_INFO

### ISSUE THREAD

**Issue by meztez** [rstudio/plumber#753]
From https://community.rstudio.com/t/pr-static-with-filename-contains-chinese-character/92499/2, a user asked if plumber supported Chinese characters directly in the PATH_INFO to serve static documents. Currently no.

This would work but it might 
 - break some stuff (all tests still pass but you never know).
 - add to execution overhead.

There are others places where this conversion could be made.

`plumber.R`
```r
    #' @description \pkg{httpuv} interface call function. (Required for \pkg{httpuv})
    #' @param req request object
    call = function(req) {
      # Set the arguments to an empty list
      req$pr <- self
      req$.internal <- new.env()
      req$PATH_INFO <- httpuv::decodeURIComponent(req$PATH_INFO)

      res <- PlumberResponse$new(private$default_serializer)
      req$args <- list()

      # maybe return a promise object
      self$serve(req, res)
    },
```

less intrusive, regular plumber routes would still not support Chinese characters
`plumber-static.R`
```r
        path <- httpuv::decodeURIComponent(path)
        abs.path <- resolve_path(direc, path)
        if (is.null(abs.path)){
          # TODO: Should this be inherited from a parent router?
          val <- private$notFoundHandler(req=req, res=res)
          return(val)
        }
```

Something to think about

**Comment by schloerke** [comment]
`req$PATH_INFO` is created by `rook`, I believe.

Submitting `测试.txt` is not valid. Chrome will encode it before submitting.

Local reprex:

```r
pr() %>% 
  pr_get("/<a>", 
    function(a, b = "", req) { 
      print(list(path = a, path_info = req$PATH_INFO, qs = b))
    } 
  ) %>% 
  pr_run(port = 8000)
```

```
curl "localhost:8000/测试.txt"
#> curl: (52) Empty reply from server

curl "localhost:8000/%E6%B5%8B%E8%AF%95.txt?b=%E6%B5%8B%E8%AF%95.txt"
#> {"path":["%E6%B5%8B%E8%AF%95.txt"],"path_info":["/%E6%B5%8B%E8%AF%95.txt"],"qs":["测试.txt"]}%
```

Seems fair to decode the path information similar to the variables when trying to read the file paths.
