### ISSUE TITLE
swagger's "example value"?

### ISSUE THREAD

**Issue by r2evans** [rstudio/plumber#768]
In some swagger interfaces, the developers provide a sample of what the output looks like. One example is
https://feed.nascar.com/swagger/ui/index#!/Drivers/Driver_GetDriversyBySeason, as in

![image](https://user-images.githubusercontent.com/5815808/107392466-b4d7a680-6ac7-11eb-9bf6-125d9abd3cef.png)

where they defined a static example of the output.

I found https://github.com/rstudio/plumber/issues/469 which suggests low-level interfacing with the swagger javascript,

```r
library(plumber)

pr <- plumb("plumber.R")

pr$run(port = 5762,
      swagger = function(pr, spec, ...){
        # Define request body for POST to /predict
        spec$paths$`/predict`$post$requestBody <- list(
          description = "New data to predict",
          required = TRUE,
          content = list(
            `application/json` = list(
              # Define JSON schema
              schema = list(
                title = "Car",
                required = c("cyl", "hp"),
                properties = list(
                  cyl = list(
                    type = "integer"
                  ),
                  hp = list(
                    type = "integer"
                  )
                )
              )
            )
          )
        )
        spec
      })
```

([source](https://github.com/sol-eng/plumber-model/blob/master/R/model-api/entrypoint.R)), though to be honest I'm not certain that that is doing what I am thinking.

Does this exist already? (if I missed it, my apologies)

If not, what is the best way to do this currently? Can we add

```r
#* @example '{"cyl":[6,4,6,8,4,4,8,6],"gear":[4,4,3,3,3,5,5,5]}'
```

(hoping that swagger may prettify it)?

**Comment by meztez** [comment]
```r
z <- list(a = 5, b = 10)

#* @post /pikapika
#* @param input:object
function(input = z) {
  sum(unlist(z))
}

#* @get /badgerbadger
function(a = 5, b = 4) {
  sum(as.integer(c(a,b)))
}

#* @post /kamehameha
#* @param leetput:object
function(leetput) {
  sum(unlist(z))
}

#* @plumber
function(pr) {
  pr$setApiSpec(function(spec) {
    spec$paths$`/kamehameha`$post$requestBody$content$`application/json`$schema$properties$leetput$example <- list(a = 2, b = 3, c = 4)
    spec
  })
}
```

You can set a default value for your parameters and it will be picked up as an example. If setting a default value is not what you want, you can modify the OpenApi manually.

**Comment by r2evans** [comment]
Oops, I see my omission. I was talking an example *output* value, not input value. The example url has both "Model" and "Example Value", frankly either or both is something I'm investigating. Thanks @meztez

**Comment by meztez** [comment]
That would be `@response`

See https://www.rplumber.io/articles/annotations.html#annotations-example-1 and https://www.rplumber.io/articles/annotations.html#equivalent-programmatic-usage-1

**Comment by r2evans** [comment]
Okay, I missed that. They look different enough that I'm guessing it's a difference in swagger versions (or something else I'm not aware of).

Thanks, sorry for the noise :-)

**Comment by meztez** [comment]
@r2evans Don't be sorry, this type of issue is an occasion to see where the doc is lacking and reflect on how the package is used. I greatly appreciate the time you took to report your interaction with plumber.
