### ISSUE TITLE
Arrow serializer

### ISSUE THREAD

**Issue by klar-C** [rstudio/plumber#776]
Hi,

Is there a serializer that would be compatible with the arrow library? I'm trying to send data from plumber to a C# project. I tried using Feather, but unlike arrow there doesn't seem to be an actively maintained Feather project anymore.

**Comment by meztez** [comment]
See the doc on creating a registering a custom serializer:

https://www.rplumber.io/reference/register_serializer.html

**Comment by schloerke** [comment]
Could use the `arrow` R package https://cran.r-project.org/web/packages/arrow/index.html within your registered serializer.
