### ISSUE TITLE
http status doesn't change to 500 after having set previously (to e.g. 406) if an error later occurs

### ISSUE THREAD

**Issue by burgikukac** [rstudio/plumber#777]
Hello, 

maybe this is a normal or documented behaviour, but it really surprised me last week.

I thought an R error will always give back a 500 http status, but the code below gives back - the already set - 406. 

My workflow was actually very similar to the second example, setting the status and then constructing the message - but due to a bug in the code, the message assembly was failed. With my false assumptions, I have only tracked the 500 errors, so this caused some trouble to the users of the API who expected a response with fixed structure.

Best regards, 

Tamas

### Example application *or* steps to reproduce the problem

```R
#* @get /echo
function(msg="", req, res) {
  res$status <- 406
  stop("OOOPS")
  list(msg = paste0("The message is: '", msg, "'"))
}


#* @get /echo2
function(msg="", req, res) {
  res$status <- 406
  list(msg = paste0("The message is: '", THIS_VARIABLE_DOES_NOT_EXIST, "'"))
}
```

**Comment by burgikukac** [comment]
I can see the in the original error handler that this is a design choice, maybe this behaviour should be emphasized in the documentation. 

I close this ticket as this is not considered a bug, and I am going to submit a feature request instead - as I still think this is undesirable for most of the users.

**Comment by meztez** [comment]
You can provide your own error handler to define the behavior.

https://www.rplumber.io/reference/pr_set_error.html
