### ISSUE TITLE
`validate_api_spec()` allows invalid specs for array parameters

### ISSUE THREAD

**Issue by karawoo** [rstudio/plumber#796]
### System details

Output of `sessioninfo::session_info()`:

```
sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.4 (2021-02-15)
 os       macOS Big Sur 10.16         
 system   x86_64, darwin17.0          
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2021-04-20                  

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version    date       lib source                          
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.2)                  
 cli           2.3.1      2021-02-23 [1] CRAN (R 4.0.2)                  
 crayon        1.4.1      2021-02-08 [1] CRAN (R 4.0.2)                  
 glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                  
 jsonlite      1.7.2      2020-12-09 [1] CRAN (R 4.0.2)                  
 later         1.1.0.1    2020-06-05 [1] CRAN (R 4.0.2)                  
 lifecycle     1.0.0      2021-02-15 [1] CRAN (R 4.0.2)                  
 magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.0.2)                  
 plumber     * 1.1.0.9000 2021-04-20 [1] Github (rstudio/plumber@98adaae)
 promises      1.2.0.1    2021-02-11 [1] CRAN (R 4.0.2)                  
 R6            2.5.0      2020-10-28 [1] CRAN (R 4.0.2)                  
 Rcpp          1.0.6      2021-01-15 [1] CRAN (R 4.0.2)                  
 rlang         0.4.10     2020-12-30 [1] CRAN (R 4.0.2)                  
 rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.0.2)                  
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.2)                  
 stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                  
 swagger       3.33.1     2020-10-02 [1] CRAN (R 4.0.2)                  
 webutils      1.1        2020-04-28 [1] CRAN (R 4.0.2)                  
 withr         2.4.1      2021-01-26 [1] CRAN (R 4.0.2)                  
 yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.2)                  

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

### Example application *or* steps to reproduce the problem

``` r
library("plumber")
specfile <- tempfile(fileext = ".yaml")
spec <- 'openapi: 3.0.0
info:
  version: "0.1.0"
  title: Test

paths:
  /test/{values}:
    get:
      parameters:
        - in: path
          required: true
          name: values
          schema:
            type: array
      responses:
        "200":
          description: OK
'
writeLines(spec, specfile)

# Use custom OpenAPI spec
pr <- pr() %>%
  pr_set_api_spec(specfile)

# Validate
validate_api_spec(pr)
#> ✔: Plumber OpenAPI Spec is valid

# View docs and see that documentation for GET /test/{values} doesn't appear
pr_run(pr)
```

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

### Describe the problem in detail

The OpenAPI spec requires that parameters that are arrays have their `items` type documented: https://swagger.io/docs/specification/data-models/data-types/#array.

In the above reprex, the spec should be invalid because it does not define the item types for the array. However `validate_api_spec()` says it is valid. When I view the docs launched by `pr_run()`, I don't see any documentation content under `GET /test/{values}` because the spec is not valid. If I fix my spec as below, then I can see the documentation:

``` r
library("plumber")
specfile <- tempfile(fileext = ".yaml")
spec <- spec <- 'openapi: 3.0.0
info:
  version: "0.1.0"
  title: Test

paths:
  /test/{values}:
    get:
      parameters:
        - in: path
          required: true
          name: values
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
'
writeLines(spec, specfile)

# Use custom OpenAPI spec
pr <- pr() %>%
  pr_set_api_spec(specfile)

# Validate
validate_api_spec(pr)
#> ✔: Plumber OpenAPI Spec is valid

pr_run(pr)
```

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I know this `validate_api_spec()` is an experimental function, but hopefully it's useful to report this!

**Comment by schloerke** [comment]
I am away from my computer, but can you call `pr$getApiSpec() %>% jsonlite::toJSON(auto_unbox =TRUE)`? (I may have the name wrong.)

Does this output have the information you are looking for?

If so, can you validate it (copy/paste) on https://editor.swagger.io/ ? 

Thank you

**Comment by karawoo** [comment]
Thanks for the suggestion, it shows an error on editor.swagger.io:

![Screen Shot 2021-04-20 at 3 49 23 PM](https://user-images.githubusercontent.com/4452678/115473414-8cb7a280-a1f0-11eb-98bc-702da4dbc3fa.png)

**Comment by schloerke** [comment]
I've filed an issue in https://github.com/APIDevTools/swagger-parser/issues/164 . I hope it is a parser issue. 

If fixed in `swagger-parser`, then it will work in a new R session (which re-downloads the node modules).

**Comment by schloerke** [comment]
Ok. This took some digging, but I think the swagger editor is incorrect with their array items requirement.

From https://github.com/APIDevTools/swagger-parser/issues/164#issuecomment-895261437, `swagger-parser` isn't going to check anything. Looking into other tools, I found https://www.npmjs.com/package/openapi-schema-validator which has added support for OAS v3.  (Live) Example: https://runkit.com/embed/fitj6h1o17e8

The Schema objects in https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object extend the [JSON Schema Specification Wright Draft 00](https://datatracker.ietf.org/doc/html/draft-zyp-json-schema-00) which points to https://datatracker.ietf.org/doc/html/draft-zyp-json-schema-00#section-5.3 
> This should be a schema or an array of schemas.  When this is an
   object/schema and the instance value is an array, all the items in
   the array must conform to this schema.  When this is an array of
   schemas and the instance value is an array, each position in the
   instance array must conform to the schema in the corresponding
   position for this array.  This called tuple typing.  When tuple
   typing is used, additional items are allowed, disallowed, or
   constrained by the additionalProperties attribute using the same
   rules as extra properties for objects.

To me, this does not say it is required. Looking at this website https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-10.3.1.2 , (talk about `items`)
> Omitting this keyword has the same assertion behavior as an empty
   schema.

The way I'm interpreting an empty schema is that it can be anything.

So in the end, I think the swagger editor is incorrectly making `items` a required element.

**Comment by schloerke** [comment]
Going to close as I believe the swagger editor is incorrectly implemented.
