### ISSUE TITLE
How to disable swagger altogether?

### ISSUE THREAD

**Issue by schloerke** [rstudio/plumber#801]
@vspinu:
> how to disable swagger altogether? Or at least the message `Running swagger Docs at ...` in the terminal?

**Comment by schloerke** [comment]
> how to disable swagger altogether?

```r
root %>% 
  pr_set_docs(FALSE) %>%
  pr_run()

# or

root %>% 
  pr_run(docs = FALSE)
```

> Or at least the message in the terminal?

```r
root %>%
  pr_run(quiet = TRUE)
```

Reference: https://www.rplumber.io/reference/pr_run.html

**Comment by vspinu** [comment]
Thanks, it worked. But I am still a bit confused. Does this mean`pr_set_docs()` is called implicitly behind my back?

**Comment by schloerke** [comment]
Can you expand on your confusion more?

**Comment by vspinu** [comment]
My expectation would be that unless I explicitly request `pr_set_docs()` in the pipeline the docs should not be generated. Currently I have to opt out of the docs with `pr_set_docs(FALSE)`, and this part is confusing. Why would plumber decide for me that I need docs, even when there is not a single documentation string in the pipeline?

**Comment by schloerke** [comment]
Ok. Thank you

The default behavior changed in v1.0.0 to enable openapi documentation by default.

https://github.com/rstudio/plumber/blob/e846cb3edf980cfea3e37325c54d69c814db2194/R/plumber.R#L95

**Comment by vspinu** [comment]
Maybe it could be a bit smarter,  for static websites, or if docs are not present don't kick it in. In any case, problem is solved. Feel free to close. Thanks!
