### ISSUE TITLE
Binding API and Swagger to all network interfaces (0.0.0.0)

### ISSUE THREAD

**Issue by virtualstaticvoid** [rstudio/plumber#813]
### System details

Output of `sessioninfo::session_info()()`:

```
> sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.1.0 (2021-05-18)
 os       Ubuntu 20.04.2 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  C.UTF-8                     
 ctype    C.UTF-8                     
 tz       UTC                         
 date     2021-07-04                  

─ Packages ───────────────────────────────────────────────────────────────────
 ! package     * version date       lib source        
 P cli           3.0.0   2021-06-30 [?] CRAN (R 4.1.0)
 P jsonlite      1.7.2   2020-12-09 [?] CRAN (R 4.1.0)
 P later         1.2.0   2021-04-23 [?] CRAN (R 4.1.0)
 P lifecycle     1.0.0   2021-02-15 [?] CRAN (R 4.1.0)
 P magrittr      2.0.1   2020-11-17 [?] CRAN (R 4.1.0)
 P plumber     * 1.1.0   2021-03-24 [?] CRAN (R 4.1.0)
 P promises      1.2.0.1 2021-02-11 [?] CRAN (R 4.1.0)
 P R6            2.5.0   2020-10-28 [?] CRAN (R 4.1.0)
 P Rcpp          1.0.6   2021-01-15 [?] CRAN (R 4.1.0)
   renv          0.13.2  2021-03-30 [1] CRAN (R 4.1.0)
 P rlang         0.4.10  2020-12-30 [?] CRAN (R 4.1.0)
 P sessioninfo   1.1.1   2018-11-05 [?] CRAN (R 4.1.0)
 P stringi       1.5.3   2020-09-09 [?] CRAN (R 4.1.0)
 P swagger       3.33.1  2020-10-02 [?] CRAN (R 4.1.0)
 P webutils      1.1     2020-04-28 [?] CRAN (R 4.1.0)
 P withr         2.4.2   2021-04-18 [?] CRAN (R 4.1.0)

[1] /app/renv/library/R-4.1/x86_64-pc-linux-gnu
[2] /tmp/Rtmp58ZfUQ/renv-system-library
```

### Example application *or* steps to reproduce the problem

```R
# app.R
library(plumber)

port <- Sys.getenv('PORT')

server <- plumb("plumber.R")

server$run(
	host = '0.0.0.0',
	port = as.numeric(port),
	docs=TRUE
)
```

Console Output:

```
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

* Project '/app' loaded. [renv 0.13.2]
> library(plumber)
> 
> port <- Sys.getenv('PORT')
> 
> server <- plumb("plumber.R")
Warning message:
Plumber tag `#* @png` is deprecated.
Use `#* @serializer png` instead. 
> 
> server$run(
+ 	host = '0.0.0.0',
+ 	port = as.numeric(port),
+ 	docs=TRUE
+ )
Running plumber API at http://0.0.0.0:8080
Running swagger Docs at http://127.0.0.1:8080/__docs__/
```

### Describe the problem in detail

The API is correctly bound to all network interfaces (as denoted by `0.0.0.0`) whereas the swagger docs are bound to `127.0.0.1` which makes them inaccessible from anywhere other than `localhost`. I.e. Only accessible on the same machine as the R process running the plumber application.

### Investigation

It appears that #376 introduced the behaviour to change the API host from `0.0.0.0` to `127.0.0.0` so that the documentation is accessible from within RStudio, based on [Shiny's server](https://github.com/rstudio/shiny/blob/95173f6/R/server.R#L781-L786) implementation.

I haven't been through the RStudio source code, but I presume it is something along the lines of using `getOption('plumber.apiHost')` to build the URL for displaying the swagger UI for a given plumber application, hence the fix in #376, but this conflates the binding configuration with the URL configuration.

### Solution

In a local development scenario, using RStudio, the plumber API and swagger docs will be available via `http://127.0.0.1/...` **irrespective** of whether the application is bound to `127.0.0.1` or `0.0.0.0`.

The fix should thus be to remove the host changing logic in [plumber](https://github.com/rstudio/plumber/pull/376/files#diff-a72e1050d6a41cd5cf70fe1d500a35edddac4c36699330920c8810acf9063da0R888-R899) (and [shiny](https://github.com/rstudio/shiny/blob/95173f6/R/server.R#L781-L786) for that matter), and then change the URL building logic in RStudio to apply the host change when reading off the `plumber.apiHost` configuration.

**Comment by schloerke** [comment]
The API is only bound to one host. The swagger docs host message is only cosmetic. If the `host` is set to `0.0.0.0`, then the docs are also set to `0.0.0.0`. 

Visiting `127.0.0.1` when the application is hosted on `0.0.0.0` _should_ work as `0.0.0.0` is a **catch-all** host.

----------------------

Are your swagger docs and all API endpoints not accessible outside of `127.0.0.1` when the API is bound to host `0.0.0.0`?

**Comment by virtualstaticvoid** [comment]
Opps, seems I had a `setOption` lurking elsewhere which set the `plumber.apiHost` to `127.0.0.1` :blush:. 

Apologies, closing the issue.

**Comment by schloerke** [comment]
Glad you found the option! 
Thank you for circling back.

**Comment by s-fleck** [comment]
This seems to be broken again with latest plumber (1.2.2). When running plumber inside my docker container i get

```
Running plumber API at http://0.0.0.0:3838
Running swagger Docs at http://127.0.0.1:3838/__docs__/
```

This seems **not to be only cosmetic** as suggested in other docs i found. The API is accessible as it should be, the swagger docs are not (but they are accessible from inside the container)
