### ISSUE TITLE
Handling of param:file for .json files

### ISSUE THREAD

**Issue by Ada-Nick** [rstudio/plumber#822]
I have a feeling this is already possible but I can't seem to implement it and haven't found what I need in the documentation.

One of my API endpoints looks like this:
```
#* endpoint name
#* @param criteria:file A json file
#* @post /endpoint
function(criteria){
    # do things with criteria
}
```

But the plumber parser always seems to coerce the JSON to a data.frame, all I want plumber to do is 
using   `<JSONlite::read_json('file_path)>` on the passed file and return a list. But is seems to be doing some extra post processing.

My curl call looks like this:
```
curl -X POST "http://localhost/endpoint" \
 -H "Accept: application/json" \
 -H "Content-Type: multipart/form-data" \
 -F "criteria=@criteria.json" 

```

My criteria.json file looks like this (the fields aren't consistent between lists hence doesn't really benefit from a data.frame class):
```
[
     {
      "variable" : "var_name",
      "description" : "test desc",
      "param_x" : 1,
      }, 
      {
      "variable" : "var_name2",
      "description" : "test desc",
      "param_y" : true,
      }, 
]
```

Plumber is returning a criteria object of class data.frame with columns variable, description, param_x and param_y. Filling gaps with NA's to create a structured data.frame. How can I disable this?

I've experimented with different param types (list, object) and different parsers (json, multi+json) but can't seem to produce the behaviour I'm expecting

**Comment by schloerke** [comment]
Seems resolved. Marking as closed. Thank you, @meztez!

--------------

... still have to get use to the new pipe `|>`. 😆
