### ISSUE TITLE
How to modify 'required' inside openapi.json in plumber endpoint definition

### ISSUE THREAD

**Issue by matmu** [rstudio/plumber#825]
In the `openapi.json` of the Swagger API documentation there is a `required` field for each query parameter of an API endpoint. In my case it is always set to `false`. Is there a way to modify it in plumber to set it to `true` for some parameters?

E.g.
```
#* Echo the parameter that was sent in
#* @param msg The message to echo back.
#* @required msg
#* @get /echo
function(msg=""){
  list(msg = paste0("The message is: '", msg, "'"))
}
```

would be awesome.

**Comment by meztez** [comment]
#* Echo the parameter that was sent in
#* @param msg* The message to echo back.
#* @get /echo
function(msg){
  list(msg = paste0("The message is: '", msg, "'"))
}
