### ISSUE TITLE
How to define a list of integer as a parameter

### ISSUE THREAD

**Issue by erossini-chi** [rstudio/plumber#826]
I'm new to `R` and `Plumber`. I saw a lot of example but none of them shows how to define an API that has a parameter as a list of number or string and use them in my code.

```
function(req, res, gender_in, age_in, spec_in, workplace_in, Q3_2_in, Q2_3_in, Q2_2_in) {
  if(gender_in == 0) {
    res$status <- 400
    return(jsonlite::unbox(data.frame(Error = 'Please ensure gender_in is an integer of value 1, 2, or 3 only.')))
  }
  
  rtn = myElaboration 
  rtn <- jsonlite::unbox(data.frame(Segment = rtn))
  return(rtn)
}
```

Thank you in advance.
Enrico

**Comment by meztez** [comment]
a list or a vector?

See https://www.rplumber.io/articles/annotations.html#more-details-on-param

Vector
```R
#* @get /vector
#* @param numbers:[int]
function(numbers) { ... }
```

List
```R
#* @post /list
#* @param characters:list
function(characters) { ... }
```

**Comment by meztez** [comment]
By the way, you do not need to do the json transformation yourself, it is handled by plumber serialization https://www.rplumber.io/articles/rendering-output.html#serializers-1

**Comment by erossini-chi** [comment]
Thank you so much for your help!

**Comment by schloerke** [comment]
Seems resolved. Marking as closed. Thank you, @meztez!
