### ISSUE TITLE
Ubuntu based Dockerfile/image

### ISSUE THREAD

**Issue by mbuet2ner** [rstudio/plumber#844]
Since I want to use plumber in production I would like to make use of the  [official Docker image](https://github.com/rstudio/plumber/blob/main/Dockerfile), which is based on the rocker project's Debian Dockerfile.

However, since nearly every RStudio Enterprise offering uses Ubuntu as a base image I would like to keep complexity in check and also use Ubuntu as a base image for the plumber Docker image. Fortunately, the Rocker project also provides [an Ubuntu base image](https://github.com/rocker-org/rocker/tree/master/r-ubuntu) as an alternative. 

I created a PR #843 with the relevant changes 👨‍🍳 .

**Comment by schloerke** [comment]
Closing due to reasoning in https://github.com/rstudio/plumber/pull/843#issuecomment-1146283030

tl/dr; The current plumber Docker file is built off of `rocker/r-ver` which uses ubuntu focal since the R version is >= 4.0 by default
