### ISSUE TITLE
good for low latency calls?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [rstudio/plumber#845]
hello, 
I was integrating R locally with NodeJS using simple shell calls to r.exe but the problem was that there were many requests to be processed and reading the hard drive so frequent is not a good practice.

I am looking for an app that runs and keeps R script alive while it waits to receive requests.

Is it possible using this package?
Just needs to run on localhost.

**Comment by meztez** [comment]
yes

**Comment by hp8wvvvgnj6asjm7** [comment]
i love it.
