### ISSUE TITLE
control a api running time

### ISSUE THREAD

**Issue by skyee1** [rstudio/plumber#859]
When I develop a API interface, I want to limit its running time.  If the specified running time is exceeded, an error message is automatically returned.  I tried using the withTimeout function in the R package R.util to do this, but it didn't work.  Is there any function to limit the running time of the API interface in this package plumber?

**Comment by schloerke** [comment]
`{plumber}` doesn't have anything to directly support this. However your endpoint's function body can make a call to `callr::r(fn, args, timeout=)` where you can set the `timeout` value. This will help you control how long a particular route can run without compromising all other computations.

https://callr.r-lib.org/reference/r.html

**Comment by schloerke** [comment]
Closing for now as `{plumber}` does not have this functionality
