### ISSUE TITLE
Well, the add-on doesn't want to install into blender

### ISSUE THREAD

**Issue by feodosiikraft** [rstudio/plumber#893]
![image](https://user-images.githubusercontent.com/120470864/207321203-f2d3257a-29d8-4093-93dc-c7f69c75eeba.png)
![image](https://user-images.githubusercontent.com/120470864/207321255-c521012d-4cbd-4067-98ff-932ba4716f9f.png)

I'm trying to install an addon as always, but it just doesn't want to show up.

But the file exists in addon folder : 
![image](https://user-images.githubusercontent.com/120470864/207321434-3175ddb1-2c14-4478-a42c-40c6edfe3ed2.png)

What should I do? Please help! Thank you very much.

**Comment by slodge** [comment]
You might have the wrong Plumber? https://github.com/lasa01/io_import_vmf/releases

**Comment by meztez** [comment]
Unrelated to this library.
