### ISSUE TITLE
Set a specific R version in docker images

### ISSUE THREAD

**Issue by jpdugo** [rstudio/plumber#894]
I am currently using inside a dockerfile the [official](https://github.com/rstudio/plumber/blob/main/Dockerfile) plumber images to run an api in production and i've noticed that the R version in the image keeps changing regularly. 
Recently, the container I was using had to be rebuilt and the new R version interfered with renv and the packages already built with another R version which I was importing from a volume.

It would be very nice to be able to specify a particular R version in the images tag.

Thank you very much

**Comment by schloerke** [comment]
Add a build arg like the example here: https://github.com/rstudio/plumber/blob/76cecc58925897c91cb88203ab485a0c512a0d26/Dockerfile#L47

**Comment by jpdugo** [comment]
@schloerke  Thank you very much for your response. 

Do you know if it will be possible in the future to specify the version of R in the same way that we can specify the version of Plumber when using the rstudio/plumber Docker image?

**Comment by schloerke** [comment]
No current plans. The matrix would be too big.

I do feel the Dockerfile is small enough that you can copy and alter how you see fit. If the current setup is restricting, please give me a toy example Dockerfile to debug with.

----------------

If there is a way to access the tags added during build time, I'd be up for changing it. Ex: Can I access `:latest` during build time? It could be a substitute for the build arg parameter.
