### ISSUE TITLE
Better filling of api url from server

### ISSUE THREAD

**Issue by slodge** [rstudio/plumber#900]
Looking at the [swagger docs generation](https://github.com/rstudio/plumber/blob/06e46f3ff5119e5f1cb8af29ef49aecb3cbb932a/R/ui.R#L14) the user needs to set an R option in order to set the server api address.

This is OK... but I'm wondering:

- could this be done via env variables? e.g. see how `renv` options/settings (are optionally env variables)[https://rstudio.github.io/renv/reference/config.html?q=settings#project-local-settings] . Supporting env variables would make configuring the url address on Posit Connect simple... and indeed Connect could even set the env variable automatically from its configured host and vanity_url?
- if the option is missing, could this be auto-detected from the request anyway? (e.g. at a trivial level it could just search and replace on `"servers":[{"url":""}] ` and replace url with the swagger host address?)

----

Aside - I think the current default `""` url is a relative url:

> If the server URL is relative, it is resolved against the server where the given OpenAPI definition file is hosted (more on that [below](https://swagger.io/docs/specification/api-host-and-base-path/#relative-urls)). 

which is OK and spec compliant... It probably works with most clients. Sadly though it doesn't work with the current rapiclient... which is why I've stumbled on it!

**Comment by meztez** [comment]
@slodge Can you set the option value from Sys.getenv() either in an .Rprofile or directly in your plumber file?

**Comment by slodge** [comment]
10 months on in struggling to remember the details here...

But I think the key here was making things easy on Posit Connect where
environment variables are the only thing users can easily access/alter

**Comment by meztez** [comment]
@slodge So adding something like

```r
options("plumber.apiURL" = Sys.getenv("PLUMBER_API_URL"))
```

At the top of a plumber file would work, right?

**Comment by slodge** [comment]
From a product user perspective, I think enabling me to set options in the
connect ui for all my apps, reports and APIs would be great. It definitely
feels better to me than making me add extra code to each of our apps.

However, I understand this is posit's package and posit's product - so I'll
leave it to the maintainers to choose 👍

**Comment by slodge** [comment]
Closing this as "won't fix"
