### ISSUE TITLE
Content-Length missing in successful requests

### ISSUE THREAD

**Issue by fmalk** [rstudio/plumber#906]
### System details

```
> pr <- plumber::plumb('/root/app-name/src/deploy/R/web_service_name.R'); pr$run(host='0.0.0.0', port=8001, swagger = TRUE)
...
Running plumber API at http://0.0.0.0:8001
[1] "check_input_data"
[1] "format_input_data"
[1] "return_output"
```

Header output (local docker desktop):
![image](https://user-images.githubusercontent.com/208820/221218055-1eed5f0e-8f18-487c-8389-a43295f5cb13.png)

Header ouput in a server environment:
![image](https://user-images.githubusercontent.com/208820/221218207-e6d699ec-624a-412c-a50e-d5a9d854a84c.png)

### Example application *or* steps to reproduce the problem

This is a dockerized R app with plumber. Above are logs I have related to plumber. It parses input and output just fine on port 8001. As I understand any R applications parsing and sending JSON would be enough to reproduce.

### Describe the problem in detail
It seems that the header "Content-Length" is only sent out in static responses, and so a JSON output after a function doesn't have that.
That seems "optional", but running containers over AWS load balancers results in fault: a load balancer *must* know a response length, or it doesn't know when transmission ended and it can let an endpoint serve another request.
I understand this is an AWS quirk, but by pumbler not handling this well my team can't deploy containers made by our R team (math analysts). Is there a reason why Content-Length header is implemented in some places (like with PR #799 ) but not while wrapping functions?

**Comment by schloerke** [comment]
> It seems that the header "Content-Length" is only sent out in static responses, and so a JSON output after a function doesn't have that.

I can confirm this with local testing.

--------------------

> running containers over AWS load balancers results in fault: a load balancer must know a response length, or it doesn't know when transmission ended and it can let an endpoint serve another request.

What is the exact message that Amazon is given you? Please include all html links in the message.

Does AWS explicitly state they need the `Content-Length` header?

---------------------------

Doesn't `Transfer-Encoding: chunked` have the content length embedded in the encoding? https://en.wikipedia.org/wiki/Chunked_transfer_encoding

**Comment by fmalk** [comment]
@schloerke I have updates regarding AWS, might be of helping to people with this issue.

AWS Load Balancer logs inform this:
`http 2023-02-24T14:47:19.842995Z app/awseb/63cadbaaaaaaaabc70 201.11111:11380 122227:8001 -1 -1 -1 502 - 1037 272 "GET http://reee.elasticbeanstalk.com:80/webservice HTTP/1.1" "PostmanRuntime/7.28.4" - - arn:aws:elasticloadbalancing "Root=1-1" "-" "-" 0 2023-02-24T14:47:19.795000Z "forward" "-" "-" "122227:8001" "-" "Ambiguous" "UndefinedContentLengthSemantics"`

However this can be relaxed at the LB:
![image](https://user-images.githubusercontent.com/208820/221268610-992133f5-e68e-4ce3-bb6e-9a2af29f25a1.png)

Which now says `"Acceptable" "GetHeadZeroContentLength"` at that same log.

You're right that `Content-Length` doesn't need to be specified if `Transfer-Encoding` is present; RFC says the two shouldn't be present at the same time. However, AWS LB doesn't take `Transfer-Encoding` into consideration, I guess.

Since we changed this, LB can connect and it's working fine. IMO since headers as it is already follow RFC good practice this shouldn't be an issue with plumber.

**Comment by schloerke** [comment]
Thank you for the followup and information, @fmalk ! 🎉
