### ISSUE TITLE
R folder loadsupport in plumber

### ISSUE THREAD

**Issue by slodge** [rstudio/plumber#913]
Is there any appetite for R folder support like in Shiny?

https://shiny.posit.co/r/reference/shiny/1.5.0/loadsupport

This would really assist with writing apps without using `source(...)` or creating a full package

**Comment by meztez** [comment]
@slodge Could you describe how you would use it?

What would be the advantage/distinction compared to?
```r
pr <- plumber::plumb(dir = ".")
```

Thank you

**Comment by slodge-work** [comment]
Our team would use it in the same way they use it in Shiny.

It would "just work" when deploying to Connect in the same way it does when they use it in Shiny.

**Comment by meztez** [comment]
Maybe a code example? It would help me understand what is required to build the feature you are referencing.

As I understand it, the loadsupport does the same think as plumb dir + run.

What am I missing?

How does relate to connect?

**Comment by slodge** [comment]
Sure....

File1 - plumber.R
```
library(plumber)

#* @apiTitle Plumber Example API
#* @apiDescription Plumber example description.

#* Do foo
#* @param msg The message to foo
#* @get /do
function(msg = "") {
  foo(msg)
}

```

File 2 - support.R
```
foo <- function(m) {
  m
}
```

Run locally in RStudio using "Run API" button:
![image](https://github.com/rstudio/plumber/assets/533662/0e04b236-fe73-483f-8e31-2531be7c41d9)

Deployed to Connect:
![image](https://github.com/rstudio/plumber/assets/533662/b4116b11-30d5-41aa-bc92-87cb94118670)

**Comment by meztez** [comment]
Oh, I get it now. Seems simple enough.

**Comment by slodge** [comment]
Also... I don't think `plumber::plumb(dir = 'Plumber/MulitFile/plumber/.') |> plumber::pr_run()` works either... I think that plumb stage only parses for endpoints?

![image](https://github.com/rstudio/plumber/assets/533662/5c3d9d9c-ca80-4af7-b66f-53249246ee50)

(Learning as I go here)

**Comment by meztez** [comment]
Idea : Maybe also support hotreload when source file change on disk.

**Comment by slodge** [comment]
> Idea : Maybe also support hotreload when source file change on disk.

Separate issue?

**Comment by schloerke** [comment]
> > Idea : Maybe also support hotreload when source file change on disk.
> 
> 
> 
> Separate issue?


Yes, please.

**Comment by slodge** [comment]
This isn't a hugely important issue. 

Respectfully closing.
