### ISSUE TITLE
Is it possible to use Plumber API with custom oAuth on Posit Connect

### ISSUE THREAD

**Issue by slodge-work** [rstudio/plumber#919]
We've been experimenting with using the sealr and jose packages in order to deploy our own oAuth authentication for plumber APIs on Connect.

This is working well - essentially all we need to do for a global auth filter is to add a filter like:

```
#* Check the request is authorised
#* @filter jwt_auth
function(req, res){

  message("PATH_INFO", req$PATH_INFO)
  
  # don't authenticate the docs
  if (
    req$PATH_INFO == "/" ||
    stringr::str_starts(req$PATH_INFO, "/__docs__/") ||
    stringr::str_ends(req$PATH_INFO,  "/openapi.json")) {
    plumber::forward()
    return()
  }

  # get the public key  
  cert <- get_certificate_cached()
  
  # simply call the strategy and forward the request and response
  sealr::authenticate(req = req, res = res, is_authed_fun = sealr::is_authed_jwt,
                      token_location = "header", pubkey = cert)

}
```
plus we have options to customise the auth at individual endpoint levels too.

This works fine when hosted locally. However, if we deploy it to Connect, then it seems like Connect intercepts and handles the oauth header - even though our Connect is set to SAML authentication, and even when we set the plumber API to "Anyone - no login required"

Is there any way to configure this Plumber API on Connect so that Connect passes through the oauth token headers to the plumber application in this case?

My motivation here is I'd like to use Connect to host our R APIs - we've got a good monitoring and deployment environment for that - but to secure those APIs using the same authentication and authorisation as our other REST APIs (written in C#, JavaScript, Python, ... and deployed across a mixture of server environments).

-------

Also asked on: https://community.rstudio.com/t/can-we-use-our-own-oauth-while-hosting-a-plumber-api-on-a-saml-configured-connect-server/175548

**Comment by meztez** [comment]
@slodge-work Like I posted in the community, I do not think this is something you can change from the plumber side.

I don't know how you have set your stuff internally. I think you are essentially trying to bypass Connect auth mechanism?
This would likely be more like a Connect hack.

Did you look into https://docs.posit.co/connect/user/api-keys/?

Why can't you use the internal connect auth? Or API keys? I'm probably missing some info.

**Comment by slodge-work** [comment]
> I do not think this is something you can change from the plumber side.

Yeah - I agree it can't run currently.

> Why can't you use the internal connect auth? Or API keys? I'm probably missing some info.

Our use case here is that we have an existing oauth system with role based authorisation and with admin processes setup to approve and maintain those roles - and that oauth system is not integrated with the SAML system which we use for Connect login. In this case, it'd be useful for us to be able to access jwt tokens and use them inside the plumber api - we'd then be able to check roles and claims inside the R, and we'd be able to pass the jwt token through to other existing REST API calls. 

We do use the internal connect auth for our simpler apps, reports and APIs where we can get away with Connect-based admin workflows, but for this particular case we don't want to set up and duplicate auth roles inside Connect (this would also require duplicating admin workflows which would involve HR and risk processes...) 

I understand this may all sound complicated... but I don't think it's unusual for Enterprises to have complicated auth. Sadly it's fairly normal that login and auth has evolved over the years and that there's more than one system running...

> I think you are essentially trying to bypass Connect auth mechanism? This would likely be more like a Connect hack.

Yes. it'd be quite helpful to have a pass-through non-authenticating mode available in Connect for this particular case... but I understand it's not a common requirement. i.e. it would be lovely if for this API we had an advanced no-auth passthrough option - e.g. something like:
![image](https://github.com/rstudio/plumber/assets/141234056/ac3b15b6-4d7c-42e3-99ff-9899e1583782)

> This would likely be more like a Connect hack.

We don't have any intention of hacking Connect (it's closed source so this is hard for us to do anyway). 

We are toying with the idea of using an alternative HTTP header (i.e. passing the JWT in some non-standard field)... but we are also considering deploying this use case outside of Connect. We don't have hosting, monitoring or CI/CD  pipelines set up for any R hosting outside of Connect currently, but that might be the way we go.

**Comment by meztez** [comment]
Could you use another another api that just do auth then redirect to connect using a single API key?

I have a few other workarounds I'm thinking about, but I don't think this is a plumber issue per say.

**Comment by slodge-work** [comment]
I asked because I wondered if it might fall inside Plumber, but I agree it's specific to Connect so happy to close.

Will raise with the Connect team and they can put it in for internal roadmap consideration (but I suspect we'll just do workarounds - probably deploying R outside Connect)

**Comment by slodge-work** [comment]
Thanks. I think that's what I meant by:

> We are toying with the idea of using an alternative HTTP header (i.e. passing the JWT in some non-standard field)

... but we have challenges here with more than one closed source system.

Anyways, I closed this above - so please don't worry further 👍
